### ISSUE TITLE
Number of bones in a partition

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/blender_niftools_addon#176]
Currently the user has no way to determine how many bones are linked to a single partition, So adding a menu function that can check this would allow for more precise exports.

**Comment by Candoran2** [comment]
Isn't this currently being done? You can control the max number of bones per partition, and for FO3 and Skyrim you can assign partitions with face maps.

**Comment by HENDRIX-ZT2** [comment]
This is done and the documentation is also up to date.
