### ISSUE TITLE
Shape Key Support

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_niftools_addon#180]
The current Blender Nif Scripts (2.5.7) needs updating to export shape key animations correctly. Although it is possible to export a shape key animation with the present scripts, it requires exporting a .nif with geometry + animation and a .kf with animation only. The resulting .nif file includes several redundant blocks.

I have created a kit that includes step by step instructions on creating a shape key animation with the current scripts. It includes a sample .blend file and associated files. You can download it from: http://www.mediafire.com/?yiv1cwc4cecsdp2

**Comment by HENDRIX-ZT2** [comment]
Pretty sure this only needs documentation and testing.
