### ISSUE TITLE
Extra Shader Textures

### ISSUE THREAD

**Issue by gforestshade** [niftools/blender_niftools_addon#213]
in function add_shader_integer_extra_datas,
TextureHelper class doesn't have a menber "EXTRA_SHADER_TEXTURES", but NifCommon class does.
https://github.com/niftools/blender_nif_plugin/blob/develop/io_scene_nif/texturesys/texture_export.py#L427
https://github.com/niftools/blender_nif_plugin/blob/develop/io_scene_nif/nif_common.py#L106

**Comment by neomonkeus** [comment]
Yes, when we were working on texture support we only focused on the map-based textures. Shader based textures weren't something we had nifs available for testing at the time. 

I haven't really done any coding on the blender plugin for several months, I would think that a quick fix would be to edit that link and set the to be ```shadername = self.EXTRA_SHADER_TEXTURES[shaderindex]``` -> ```shadername = self.nif_export.EXTRA_SHADER_TEXTURES``` based on the import side of things - https://github.com/niftools/blender_nif_plugin/blob/develop/io_scene_nif/texturesys/texture_import.py#L116

I am not sure if there should be a similar lookup map.
