### ISSUE TITLE
Dismemberment PF_START_NET_BONESET Flag

### ISSUE THREAD

**Issue by CunningMoss6833** [niftools/blender_niftools_addon#263]
@niftools/blender-nif-plugin-reviewer 

## Issue Overview 
The Boneset flag does not get set on the first dismemberment partition or the wrist gets moved before the body partition when exporting armatures

### Blender Nif Plugin Version Info
nif plugin Ver: 2.6.0a0.dev4-20-jun-16 with updates from issues:
https://github.com/niftools/blender_nif_plugin/pull/251
https://github.com/niftools/blender_nif_plugin/pull/252

### Blender Version Info
2.78

### Platform information
Windows Vista

## Context
This is more of an enhancement request as there is an easy workaround. This issues causes the user to use NifScope to edit the partition flags after export

## Steps to Reproduce
1. import stock Skyrim main body clothing, malebody_0.nif will work
2. export the body
Settings:
	Scale = 10 (differs on personal preference)
	Skyrim
	Flatten Skin
	Max Partition Bones = 24 <- Set this to the number of bones in your mesh]
 #. 

## Expected Result
The dismemberment list stays in the Blender listed order or the PF_START_NET_BONESET Flag gets set on the first dismemberment partition.

## Actual Result
The Boneset flag does not get set on the first dismemberment partition or the wrist gets moved before the body partition when exporting armatures. 

## Possible Fix
I am not a developer and I did not look at the code yet but my guess is that the export order is not correct. That, or add some code to verify the BONSET flag gets set on the first and only the first dismemberment partition.

## Screenshot
![dismembermentflag2](https://cloud.githubusercontent.com/assets/26804785/24531130/4e6184a6-157c-11e7-99e9-6e0bd77a9a51.jpg)
![dismembermentflag1](https://cloud.githubusercontent.com/assets/26804785/24531140/5bd3c04a-157c-11e7-81fe-b701291bedd2.jpg)

## Logs and Files
There are no error codes returned

### Info Bar Output
Output from the Info View, available at top of Blender viewport, drag to expand
[Infoview.txt](https://github.com/niftools/blender_nif_plugin/files/884140/Infoview.txt)

### Console Output
Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console - I am not figuring out how to do this

### Blend File
[test.zip](https://github.com/niftools/blender_nif_plugin/files/884132/test.zip)

### Nif File
This is what shouldn't be ... the BONESET flag should be on the top most partition.
[test.zip](https://github.com/niftools/blender_nif_plugin/files/884168/test.zip)

## Similar Known Issues
Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues

## Additional Information
Anything else you feel is relevant

**Comment by neomonkeus** [comment]
Yeah this area needs to be re-written.
This issue is partially dealt with in #250
