### ISSUE TITLE
Cannot Import a Model .nif

### ISSUE THREAD

**Issue by SuggestName** [niftools/blender_niftools_addon#384]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
[Provide a general introduction to the issue and why it is relevant to this repository]
I got this erro while im trying to load a .nif model

### Blender Niftools Addon Version Info
[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]

### Blender Version Info
[Provide information on which version of Blender the issue is seen]

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
[Ordered list of the steps required for recreating the issue, including settings]
 #. 

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]
```
Traceback (most recent call last):
  File "C:\Users\dudu1\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nif\operators\nif_import_op.py", line 125, in execute
    return nif_import.NifImport(self, context).execute()
  File "C:\Users\dudu1\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nif\nif_import.py", line 73, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\dudu1\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nif\nif_import.py", line 142, in load_files
    scene.import_version_info(NifData.data)
  File "C:\Users\dudu1\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_nif\modules\nif_import\scene\__init__.py", line 75, in import_version_info
    NifLog.warn(f"Game set to '{possible_games[0]}', but multiple games qualified")
NameError: name 'NifLog' is not defined

location: <unknown location>:-1
```

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[Attach input or output files, samples of what the expected output should be and reproducing the issue]

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by neomonkeus** [comment]
Please complete the template correctly.
