### ISSUE TITLE
The URL for release "v2.6.0a dev 4" says "v2.6.0a dev 6" instead

### ISSUE THREAD

**Issue by Hasselshoff** [niftools/blender_niftools_addon#394]
Not a big deal at all, but I just wanted to point out what is likely a spelling error in the URL for release v2.6.0a dev 4. It was a harmless mistake until it confused a few of my mates into thinking we had the wrong version. Anyways, keep up the good work!

![image](https://user-images.githubusercontent.com/69090157/100796140-320edd00-33ee-11eb-80b1-508fba83ae18.png)

**Comment by neomonkeus** [comment]
I plan to delete that tag when there are a few more versions out.
Not going to go through the effort of retagging and rebuilding in this case.
