### ISSUE TITLE
Animation imported with 'blank' keyframes containing no transformation.

### ISSUE THREAD

**Issue by Hasselshoff** [niftools/blender_niftools_addon#398]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Importing a .kf animation file using latest Blender NifTools Addon release v0.0.2 always results in 'blank' keyframes. 

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
v0.0.2

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**

### Platform information
**[Provide a brief overview of what OS your running on]**

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
The import does not throw any noticeable errors on-screen or in Blender Info Log, but playing back the animation results in no transformation of the model, despite the animation being known to contain movement. 

The same .nif (armature) & .kf (animation) files import successfully using NifTools addon v2.6.0 dev4. Several friends of mine have independently experienced (and are still experiencing) the issue.

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

## Expected Result
**[Describe what you expected to have resulted from this process]**

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**
Recording of an example import using v0.0.2:
https://i.imgur.com/iauVQ10.gifv

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**
Screenshot of Blender Info Log after importing .kf animation file that results in blank keyframes:
![no error in Blender Info Log after importing  kf animation file that results in blank keyframes](https://user-images.githubusercontent.com/69090157/101462146-d7074980-3909-11eb-8763-d49465cf4772.jpg)

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by HENDRIX-ZT2** [comment]
Fill out the whole template. Most importantly, submit the NIF and KF file in question.

**Comment by HENDRIX-ZT2** [comment]
From the screencap it looks like the animation is imported alright, it just isn't attached to the armature because you didn't select it. The keys are definitely not 'blank'.

**Comment by HENDRIX-ZT2** [comment]
Oh yeah the refactor did introduce an error:

channel data paths have one " too much:
pose.bones["Bip01 Calf.R""].rotation_quaternion

**Comment by HENDRIX-ZT2** [comment]
Issue is solved, can be closed.

**Comment by neomonkeus** [comment]
Will close when building v0.0.4

**Comment by Hasselshoff** [comment]
Terribly sorry, it was late and I completely spaced on the template. Thanks for looking into it!

**Comment by neomonkeus** [comment]
Included in v0.0.3, closing
