### ISSUE TITLE
Skin partitioning failing silently ?

### ISSUE THREAD

**Issue by kin-yen** [niftools/blender_niftools_addon#400]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
This might not be a bug. I am not sure, and if so - i'm sorry. If I should do more steps to try and narrow this down please let me know. The referenced nifs and .blend are in the attached zip.

The NOT_WORKING.nif, which is a duplicate of WORKING.nif with transferred weights, using the same armature fails to work in game (T poses, seems unweighted, skyrim SE). Exporting WORKING.nif works as expected in game.

Comparing the two nifs in nifskope they are similar except:
* NOT_WORKING was exported with one skin partition instead of three - all verts are assigned to SBP_32_body in blender. 
* The 'part flag' of NOT_WORKING.nif's skin partition is not being set (0), setting it to Start Net Boneset and Editor Visible in nifskope doesn't help.

If I import NOT_WORKING into outfit studio, delete all bones, import a reference and copy reference weights it works (Not_working_OS_reweight.nif). Weight painting and partitions both look good for NOT_WORKING.nif in outfit studio before doing this. Simply importing -> copying reference weights -> exporting in outfit studio does not work, bones have to be _deleted_ and then copied from reference for it to work.

I'm suspecting it's failing at creating the skin partition (but I really dont know). From the blender console log it gives no hint at failure and inspecting/comparing the two nifs in nifskope doesn't show any glaring differences except for the part flag not being set. 

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
Latest develop branch (commit 6175c28) (pulled 10/12 - 2020), had same issue on latest release v 0.0.2
Inspected nifs in Nifskope 2.0 Dev 7

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
2.83

### Platform information
**[Provide a brief overview of what OS your running on]**
Win 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 
1. Export the objects in the .blend file as nif. (50 max part. bones, 4 max vert bones, skin partition checked)
2. Test in game

## Expected Result
**[Describe what you expected to have resulted from this process]**
Export failure (if skin partitioning or something else is actually failing here)

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
-No hint at error or fail in the blender console on export
 -Nifs look reasonably similar in nifskope except for part flag not being set
-T-poses in game.

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**
NOT_WORKING.nif
![ScreenShot0](https://user-images.githubusercontent.com/75856920/101955123-8dff1000-3bfd-11eb-98e2-e653f3b84f39.png)
WORKING.nif
![ScreenShot1](https://user-images.githubusercontent.com/75856920/101955158-9a836880-3bfd-11eb-8f8c-00c89f9abc76.png)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
[Example_nifs_blendfile.zip](https://github.com/niftools/blender_niftools_addon/files/5681560/Example_nifs_blendfile.zip)

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**
Example nifs are the cbbe female body, so perhaps (slightly) nsfw.

**Comment by neomonkeus** [comment]
Probably the best bug report I have seen 🚀

**Comment by OphCom** [comment]
Update to this one, what salvaged my nif setup was swapping the skeleton into another one and repainting.

I had tried to join two separate rigs to get the bones from both, but I could never get it to work properly through multiple ways of exporting.
In the end I just went with one imported skeleton and added bones to it manually that I needed, repainting and now it works just fine, partitioning and all.
I don't know exactly what caused the behaviour but probably something about scalings or orientation in the two individual armatures I merged (hard to figure out after they've been merged).

**Comment by Candoran2** [comment]
Best I can tell, the posted blend file exports just fine (at least now, can't confirm how it did in the past). One of the two NiTriShapes (Body) didn't move with the bones because it had the `Environment Map` Shader type instead of `Skin Tint`, and it crashed the game after that due to wrong shader flags. The other NiTriShape (3BBB) seemed to work just fine from the get-go.

**Comment by neomonkeus** [comment]
Closing as per @Candoran2's comments
