### ISSUE TITLE
Export to skyrim nif missing Has_Tangents bit

### ISSUE THREAD

**Issue by BadDogSkyrim** [niftools/blender_niftools_addon#404]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Trying to do a round trip from Skyrim LE nif -> Blender -> Skyrim fails. Nif is "Saviors Hide". The exported nif is missing the Has_Tangents bit in the BS_Vector_Flags field of the exported NiTriShapeData. It may have other problems as well but one thing at a time.

I didn't do any edits in blender except to confirm that the import seemed correct.

I've been using 2.49 and 2.79 niftools import/export for years but I'm a total noob on blender 2.9  so if it looks like an obvious error on my part, it probably is.

### Blender Niftools Addon Version Info
v0.0.3

### Blender Version Info
2.91

### Platform information
Windows 10

## Context
This is a basic task for modding skyrim--import nif, make changes, export.

## Steps to Reproduce

1. Use import tool to bring nif into blender, taking all defaults
2. Result seems basically correct though the normal map doesn't seem to be connected in the Shaders panel the way I'd expect. But that's part of the new blender features I don't know enough about to be sure.
3. Export to nif, taking all defaults.

## Expected Result
A usable nif for skyrim, preferably identical to the original, but working anyway.

## Actual Result
The exported nif is missing the Has_Tangents bit in the BS_Vector_Flags field of the exported NiTriShapeData. It may have other problems as well but one thing at a time.

## Possible Fix
Maybe there's a setting in blender that would trigger exporting tangents? 

## Screenshot
N/A

## Logs and Files
Log in the console output

### Info Bar Output
Couldn't find it

### Console Output
[skyrimarmor.log](https://github.com/niftools/blender_niftools_addon/files/5721055/skyrimarmor.log)

### Blend File
N/A, made no changes

### Nif File
[skyrimarmor.zip](https://github.com/niftools/blender_niftools_addon/files/5721047/skyrimarmor.zip)

## Similar Known Issues
None

## Additional Information
None

**Comment by BadDogSkyrim** [comment]
It occurred to me to wonder if it happened to all armors (seems like it does). And that it might be helpful to you to [have the files](https://drive.google.com/drive/folders/1RzCVwM_BmQOzB32Uoi_UvHToaXqJ659B?usp=sharing). CuirassLight_1.nif is the input, untitled.nif is the output.[](url)

**Comment by neomonkeus** [comment]
I have readded the original template as several sections were removed, including the ones which look for reference files.
Feel free to add them in the appropriate section.

**Comment by BadDogSkyrim** [comment]
Okay, filled out all the parts. I thought brevity would be helpful.

Is there a help/comments/discussion place I could be using? Documentation?

Would you like help writing documentation? I'd be willing to put some time into that.
