### ISSUE TITLE
Cannot enable the addon

### ISSUE THREAD

**Issue by ZeroJyllmeiko** [niftools/blender_niftools_addon#406]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
I cannot enable the addon at all for some unknown reason.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
0.0.3

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
2.79

### Platform information
**[Provide a brief overview of what OS your running on]**
Windows 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. Download Addon from File ---> Attempt to enable.

## Expected Result
**[Describe what you expected to have resulted from this process]**
Addon should be enabled

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
Message pops up:
```
Traceback (most recent call last):
	File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable mod = __import__(module_name)
	File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\addona\io_scene-niftools\__init__.py", line 62 NifLog.info(f"Loading: Blender Niftools Addon: {version.read()}")

SyntaxError: invalid syntax
```

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by neomonkeus** [comment]
v0.0.3 is not compatible with Blender 2.7x.

Also not sure what you used to install it, but it should have been in the `addons` not `addona` , unless its a language thing.
```
	File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.79\scripts\addona\io_scene-niftools\__init__.py", line 62 NifLog.info(f"Loading: Blender Niftools Addon: {version.read()}")
```

**Comment by ZeroJyllmeiko** [comment]
First off, I didn't know what version to get.

Second, yeah, the 'addona' part was a typo. I couldn't exactly copy and paste it.

**Comment by neomonkeus** [comment]
Did you install from the zip?
I am surprised that it installed, as we specifically define a min version so it should have thrown an incompatible version.

Also anything blocking you from upgrading?
