### ISSUE TITLE
Can't export nif

### ISSUE THREAD

**Issue by ehcho0222** [niftools/blender_niftools_addon#408]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [x] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
I wanted to export blend to nif, but there was an error and it produced corrupt nif.
### Blender Niftools Addon Version Info
Blender Addon version 0.0.3

### Blender Version Info
This issue can be seen on Blender 2.91

### Platform information
I am running Windows 10 20H2.

## Steps to Reproduce
You could try to export the nif, after installing the addon.

## Expected Result
The nif file will be exported.

## Actual Result
The program will throw an error, and the resulting nif file will be corrupt and very small in size.

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**
```
Python: Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 155, in execute
    return NifExport(self, context).execute()
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_export.py", line 333, in execute
    data.write(stream)
  File "C:\Users\<username>\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1522, in write
    self._block_index_dct[block]))
struct.error: argument out of range
```

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by OphCom** [comment]
Not dev, but have had this error. Are you exporting for skyrim? Check the game settings under scene properties, see screenshot below. If these are wrong you can get that error (don't know if it will solve your particular problem though).

![niftools_settings](https://user-images.githubusercontent.com/75856920/104838181-89431100-58b9-11eb-8496-7ed1a52009d5.png)

**Comment by neomonkeus** [comment]
@ehcho0222 Can you update the issue description to include the files to enable us to reproduce the issue.
