### ISSUE TITLE
Kf export

### ISSUE THREAD

**Issue by Gorgotem** [niftools/blender_niftools_addon#410]
**Is your feature request related to a problem? Please describe.**
The Kf import feature works perfectly, so, an export Kf feature will be perfect for animators, due to de easy animator workflow in blender. 

**Describe the solution you'd like**
This feature was abaliable in previous version (blender 2.49, blender 2.79) So i hope it will be available soon

**Describe alternatives you've considered**

**Additional context**

**Comment by neomonkeus** [comment]
Re-added the template.
