### ISSUE TITLE
Skinning to nodes that are not child of SkinInstance root

### ISSUE THREAD

**Issue by Fictitious-Rotor** [niftools/blender_niftools_addon#419]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [X] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
The attached nif file fails to import.

### Blender Niftools Addon Version Info

v0.0.4
### Blender Version Info
Blender 2.92

### Platform information
Windows 10

## Context
Importing nif files is one of the advertised features

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**

1. Open Blender
2. Import nif file
3. Choose attached nif file

## Expected Result
Nif file loads

## Actual Result
Error message

## Possible Fix
Something about the formatting of this nif file has presumably confounded the importer

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**
```
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.4(running on Blender 2.92.0, PyFFI 2.2.4.dev3)
niftools:INFO:Importing D:\Steam\steamapps\common\Skyrim\Data\SKSE\Plugins\CharGen\Head_3-18-2021_18-1-25.nif
niftools:INFO:NIF file version: 14020007
niftools:INFO:Reading file
niftools:INFO:Importing data
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 0.100000
pyffi.toaster:INFO:  ~~~ BSFadeNode [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC Head [Head]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC Spine2 [Spn2]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [BSFaceGenNiNodeSkinned] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [MaleHeadArgonian] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ BSDismemberSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:        ~~~ BSLightingShaderProperty [] ~~~
pyffi.toaster:INFO:          ~~~ BSShaderTextureSet [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [MaleMouthArgonian] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:        ~~~ BSLightingShaderProperty [] ~~~
pyffi.toaster:INFO:          ~~~ BSShaderTextureSet [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [MaleEyesArgonian] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:          ~~~ NiAdditionalGeometryData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:        ~~~ BSLightingShaderProperty [] ~~~
pyffi.toaster:INFO:          ~~~ BSShaderTextureSet [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [BSKHairArgonianMale07] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:        ~~~ BSLightingShaderProperty [] ~~~
pyffi.toaster:INFO:          ~~~ BSShaderTextureSet [] ~~~
Read prefs: C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend
Python: Traceback (most recent call last):
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\nif_import.py", line 135, in execute
    self.import_root(root)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\nif_import.py", line 165, in import_root
    self.armaturehelper.mark_armatures_bones(root_block)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 356, in mark_armatures_bones
    self.mark_armatures_bones(child)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 356, in mark_armatures_bones
    self.mark_armatures_bones(child)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 348, in mark_armatures_bones
    self.complete_bone_tree(boneBlock, skelroot)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 389, in complete_bone_tree
    self.complete_bone_tree(boneparent, skelroot)
  File "C:\Users\Caute\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 385, in complete_bone_tree
    NifLog.debug(f"'{boneparent.name}' is a bone of armature '{skelroot.name}'")
AttributeError: 'NoneType' object has no attribute 'name'
location: <unknown location>:-1
```
[error.log](https://github.com/niftools/blender_niftools_addon/files/6173849/error.log)

### Blend File
**[Attach the blend file if the issue is reproducible]**
No Blender context necessary

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
[Head_3-18-2021_19-23-12.zip](https://github.com/niftools/blender_niftools_addon/files/6173851/Head_3-18-2021_19-23-12.zip)

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**
[errorafterclose.log](https://github.com/niftools/blender_niftools_addon/files/6173897/errorafterclose.log)

**Comment by Candoran2** [comment]
The 'problem' in this nif file, which the importer has trouble with, is that the bones of the BS/NiSkinInstances are _not_ children of the NiNode which is the Skeleton Root of that same BS/NiSkinInstance. The importer (and the exporter) of rely on that.
The real problem is then how do we import and export this is such a way that it reflects that structure (the bones being children of something else than their Skeleton Root).

What maybe could be a way would be to have the name of the Armature indicate which object should be the skeleton root upon export - if the object with the corresponding name is empty (i.e. it would be exported as a NiNode) then that becomes the skeleton root upon export, otherwise it's exported as normal. However, I'm a bit wary of doing things that might break then, since I'm not too familiar with the armature import/export system, or the bone system in Blender in general.

**Comment by HENDRIX-ZT2** [comment]
I would however argue that this nif is unusable as is.

**Comment by HENDRIX-ZT2** [comment]
Interesting that the bones have no transforms!

**Comment by Candoran2** [comment]
I think this is fixed with the latest release.
