### ISSUE TITLE
Docs link not working

### ISSUE THREAD

**Issue by Gazareth** [niftools/blender_niftools_addon#431]
**Is your feature request related to a problem? Please describe.**
Docs link in the readme:
https://blender-niftools-addon.readthedocs.io takes you to a 404

**Describe the solution you'd like**
The docs to be available

**Describe alternatives you've considered**
Readthedocs vs Github pages.

**Additional context**

**Comment by neomonkeus** [comment]
I have reconfigured readthedocs due to the recent repo rename, however we haven't built on read the docs for a few years.
Needs further work and not even sure whether we want to go with using readthedocs vs gh docs.
Moving this to a feature request based which direction we want to go.
