### ISSUE TITLE
Oblivion animation exported, Nifskope error: "<empty>"

### ISSUE THREAD

**Issue by Gazareth** [niftools/blender_niftools_addon#432]
# Issue Overview
I'm trying to modify some existing animations for TES IV: Oblivion. I'm just testing out the workflow so I've imported a completely fresh version of an animation (blockhit.kf) and exported, then tried to view it in nifskope, but I am getting an error which just says: `<empty>`

Upon further investigation using an older version of nifskope (<= 1.3.3) I get a bit more information about the error:
"The following controlled nodes were not found in the nif: `<empty>`"

![image](https://user-images.githubusercontent.com/11911259/113475190-f5222800-946b-11eb-8c47-8978b7b964a5.png)

### Blender Niftools Addon Version Info
**0.0.5** but also **0.0.4**.

(This is a separate issue but just so we're on the same page)
It says in Blender it's on **0.0.4**, so I clicked auto update and it said it will update to 0.0.5; it appeared to update and then restarted Blender, but it still says 0.0.4, and if I click 'check for updates' it says "error checking for updates".

### Blender Version Info
2.92.0

### Platform information
Windows 10 Home 64-bit

## Context
I've attached a zip with all the necessary files to reproduce below, but for more info:

I am using the skeleton found here: https://www.nexusmods.com/oblivion/mods/49394

And the kf animation file is extracted from the oblivion game files using the BSA unpacker:
https://www.nexusmods.com/oblivion/mods/3117

## Steps to Reproduce

1. Open Blender 2.92.0
2. Import the skeleton `.nif` using blender_niftools_addon (0.0.4/0.0.5)
3. Import the animation `.kf` using blender_niftools_addon (0.0.4/0.0.5)
4. Export a `kf` using blender_niftools_addon (0.0.4/0.0.5)
5. Open Nifskope, load the skeleton and then exported animation (1.1.3, 1.2.0a2, 2.0.dev7)
6. See error:
![image](https://user-images.githubusercontent.com/11911259/113475551-4af7cf80-946e-11eb-98ca-94804b85be9f.png)

## Expected Result
The exported animation should load into Nifskope successfully.

## Actual Result
The exported animation does not load into Nifskope.

## Possible Fix
Find out why the controlled node `<empty>` is not present.

## Logs and Files
I'm not sure how to do this for Nifskope, but I've included the blender console output below.

### Info Bar Output
It just said "Finished"

### Console Output
**Procedure:**
1. Open blender
2. Import skeleton nif
3. Import animation nif
4. Export 'animation only' kf file

**Log:**
[blender_niftools_import_export_animation_20210403.txt](https://github.com/niftools/blender_niftools_addon/files/6252354/blender_niftools_import_export_animation_20210403.txt)

### Blend File, Nif File & KF files
[Oblivion_Import_Export_AnimationFiles.zip](https://github.com/niftools/blender_niftools_addon/files/6252363/Oblivion_Import_Export_AnimationFiles.zip)

## Additional Information
Happy to put some time into contributing a fix for this if someone can point me in the right direction.
I'm looking to create lots of animations for a mod I'm working on so I'd like to be on the latest versions of the tools available.

**Comment by SubhadeepG** [comment]
I have looked at the code and it does not export all the necessary animation data. You have to use another tool until it is fixed.

**Comment by neomonkeus** [comment]
Thanks for filling out the template, its always appreciated when as much info as possible is provided.

**Comment by neomonkeus** [comment]
Found the issue with the plugin showing up as v0.0.4, thanks for noticing that.
I have re-released v0.0.5 so you can auto-upgrade to that version.

**Comment by HENDRIX-ZT2** [comment]
The string palette is not being written.

**Comment by HENDRIX-ZT2** [comment]
Idk why this didn't autoclose with the merge.

**Comment by neomonkeus** [comment]
> Idk why this didn't autoclose with the merge.

For future reference you need to say `Closes XXX`
