### ISSUE TITLE
kf export file corrupted

### ISSUE THREAD

**Issue by FabianAlt93** [niftools/blender_niftools_addon#445]
I import an .kf Oblivion animation modified it a bit and exported it again as .kf.
When I create a new scene in blender and import that freshly exported kf animation it doesn't do anything.

The file is also just 2 kb big, the original animation is 7 kb.

**Comment by Gazareth** [comment]
Could be related to #432

**Comment by weds4** [comment]
I am experiencing a similar issue, only with Skyrim LE animations. I import the .kf and then export it, and in-game the camera position is misplace and jumps around when moving. I converted the original animation and the exported one to xml, and there seem to be significant differences in the files. One whole hkobject is misisng, as well as the number of Transform Tracks being less in the exported animation (and other differences).

**Comment by HENDRIX-ZT2** [comment]
Template has been removed, critical information is missing, closed.
