### ISSUE TITLE
Blender 2.93 and Fallout 4

### ISSUE THREAD

**Issue by Official-Husko** [niftools/blender_niftools_addon#447]
Support for blender version 2.93 and Fallout 4?

Im getting an error and wanted to ask if you will add support for blender 2.93 or if i need to use a older version. I haven't seen a specific version somewhere so which one would i need exactly?

Edit: from what i have seen there is no other real way to export to nif since the 3ds variant is completely broken and outdated. That's why im asking.

**Comment by neomonkeus** [comment]
Duplicates #405
