### ISSUE TITLE
Error while export, Game not set

### ISSUE THREAD

**Issue by ellb6** [niftools/blender_niftools_addon#449]
@niftools/blender-niftools-addon-reviewer -

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
blender fails to export a relatively simple mesh to a nif format 

### Blender Niftools Addon Version Info
0.06

### Blender Version Info
2.93

### Platform information
windows 10 64 bit 

## Context
fail to export a mesh to nif format 

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. open the blend file 
click on export and nif format 

## Expected Result
**[Describe what you expected to have resulted from this process]**
a nif file should have been exported 
## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
just gives an error and it gives out a nif but it is invalid 
## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**
maybe because it has no textures the object?
## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.6(running on Blender 2.93.1, PyFFI 2.2.4.dev3)
niftools:INFO:Exporting C:\Users\Elliott\Documents\morfa bay piece.nif
niftools:INFO:Exporting
niftools:INFO:Exporting geometry and animation
niftools:INFO:Writing NIF version 0x00000000
niftools:INFO:Exporting <bpy_struct, Object("Cube") at 0x0000016BEC7A0808>
niftools:INFO:Exporting <bpy_struct, Object("Cube") at 0x0000016BEC7A0808> as NiTriShape block
niftools:INFO:Exporting NiStencilProperty block
niftools:INFO:Exporting NiSpecularProperty block
niftools:INFO:Exporting NiMaterialProperty block
niftools:INFO:Exporting NiTexturingProperty block
niftools:INFO:Exporting <bpy_struct, Object("Cube") at 0x0000016BEC7A0808> as NiTriShapeData block
niftools:INFO:Checking collision
niftools:INFO:Checking controllers
niftools:INFO:Scale Correction set to 10
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 10.000000
pyffi.toaster:INFO:  ~~~ NiTriShape [Cube] ~~~
pyffi.toaster:INFO:    ~~~ NiBinaryExtraData [Tangent space (binormal & tangent vectors)] ~~~
pyffi.toaster:INFO:    ~~~ NiStencilProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiSpecularProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiMaterialProperty [Material] ~~~
pyffi.toaster:INFO:    ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiTriShapeData [] ~~~
niftools:INFO:Writing .nif file
Python: Traceback (most recent call last):
  File "C:\Users\Elliott\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\Elliott\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_niftools\nif_export.py", line 291, in execute
    data.write(stream)
  File "C:\Users\Elliott\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1521, in write
    stream.write(struct.pack(self._byte_order + 'i',
struct.error: argument out of range

location: <unknown location>:-1

### Blend File
**[Attach the blend file if the issue is reproducible]**
[
[morfa bay piece.zip](https://github.com/niftools/blender_niftools_addon/files/6801868/morfa.bay.piece.zip)
[morfa bay piece.zip](https://github.com/niftools/blender_niftools_addon/files/6801872/morfa.bay.piece.zip)
](url)
### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

![image](https://user-images.githubusercontent.com/87315982/125292833-bfb69180-e31a-11eb-992e-554684308753.png)
can anyone help?

**Comment by neomonkeus** [comment]
@ellb6 I have put back in the template we use, please fill it out with the required details otherwise we can't help with your issue.

**Comment by Candoran2** [comment]
That looks like you didn't set the game in the scene tab, leaving the nif version to be 0.

**Comment by neomonkeus** [comment]
> That looks like you didn't set the game in the scene tab, leaving the nif version to be 0.

Should we set a default or warn the user when not set. We have seen a few issues reported around this.

**Comment by Candoran2** [comment]
> > That looks like you didn't set the game in the scene tab, leaving the nif version to be 0.
> 
> Should we set a default or warn the user when not set. We have seen a few issues reported around this.

I think it might be useful to have a none/not-set game as the default. That way, we can easily error/warn if they haven't selected something and the user is forced to choose a setting.
