### ISSUE TITLE
Cannot import X3D file (with texture) into Blender

### ISSUE THREAD

**Issue by phillipsconsulting** [niftools/blender_niftools_addon#451]
Hello,

Am trying to import the attached X3D file into Blender (indexedfacedset.x3d, see below since cannot attach), the purpose being whether I can assign different textures on each face of a IndexedFaceSet type). This file is just an attempt to get a some texture to show up somewhere. However, I cannot get past an import issue (please see the stack trace in import_issue.png). I've attached Blender version info in the file about_blender.png. The texture file is also attached here (I've tried both JPG and PNG files). The texturefile(s) and X3D are all hosted locally. When I remove all references to the texture (the Appearance block, texCoordIndex and TextureCoordinate attribute / element), the import is successful.

Is this a known issue or is it me?

import_issue.jpg...
![import_issue](https://user-images.githubusercontent.com/71787368/128944017-fe06410a-11a6-4b79-ac39-8d6c54b3ed43.png)

about_blender.png...
![about_blender](https://user-images.githubusercontent.com/71787368/128944044-9ddd494b-6f52-4818-a1a2-430a04135028.png)

Thanks,

Matthew

indexedfacedset.x3d...

```xml
<?xml version='1.0' encoding='UTF-8'?>
<X3D profile='Immersive'>
  <Scene>
  <Shape>
  <Appearance>
  <Material/>
  <ImageTexture url='./texture.jpg'/>
  </Appearance>
<IndexedFaceSet ccw='true'
                colorIndex='0, 1, 0, -1, 0, 2, 0, -1'
                colorPerVertex='true'
                convex='true'
                coordIndex='0, 1, 3, -1, 0, 2, 3, -1'
                creaseAngle='0.0'
                normalIndex='0, 1, 3, -1, 0, 2, 3, -1'
                normalPerVertex='true'
                solid='true'
				texCoordIndex='0, 1, 3, -1, 0, 2, 3, -1'>
  <Color color='0.2 0.2 0.2, 0.4 0.4 0.4, 0.6 0.6 0.6'/>
  <Coordinate point='0 0 0, 1 0 0, 1 0 -1, 0.5 1 0'/>
  <Normal vector='0 0 1, 0 0 1, 0 0 1, 0 0 1'/>
  <TextureCoordinate point='0 0 0, 1 0 0, 1 0 -1, 0.5 1 0'/>
</IndexedFaceSet>
</Shape>
  </Scene>
</X3D>

```

**Comment by phillipsconsulting** [comment]
Here's the texture file...
 
![texture](https://user-images.githubusercontent.com/71787368/128944635-b4938b51-daae-4704-982e-e23635ee4e93.jpg)

**Comment by neomonkeus** [comment]
This format is not related to this addon. You should contact the owner of the addon which corresponds to x3d support
