### ISSUE TITLE
Armature guess_orientation can guess wrong

### ISSUE THREAD

**Issue by korri123** [niftools/blender_niftools_addon#454]
[battlerifle.zip](https://github.com/niftools/blender_niftools_addon/files/7150692/battlerifle.zip)
Blender version: 2.92
Niftools addon version: 0.07

For attached nif it will guess that 'X' and 'Y' are forward and up while 'Y' and 'Z' are the correct orientations.
Attached is a .nif file to import. 

https://github.com/niftools/blender_niftools_addon/blob/master/io_scene_niftools/modules/nif_import/armature/__init__.py#L155

How to reproduce issue:
1. Import weapon with nif import and process `Everything`
2. Import weapon skeleton with nif import and process `Skeleton only`
3. Notice that `ProjectileNode` is not parallel to the guns barrel.

**Comment by HENDRIX-ZT2** [comment]
Not much we can do I guess. It should not be a problem since it is merely the visualization in blender. Export will be correct.

**Comment by HENDRIX-ZT2** [comment]
There's no way to tell the 'correct' orientation of bones in this nif as there is no parenting chain that could give an indication of what 'forward' is.
