### ISSUE TITLE
Add animation support + Fix Merging of Materials to Megami Tensei: Imagine

### ISSUE THREAD

**Issue by TheRealHitoshura** [niftools/blender_niftools_addon#479]
Hello and Good Afternoon!

![ImagineAnimationExport](https://user-images.githubusercontent.com/49658543/140185729-5399f488-33ea-4667-90be-6bb8987ca565.png)
![numo](https://user-images.githubusercontent.com/49658543/140185780-94e3fd0a-a7ee-4421-b7f5-edbadf7641a9.png)

First and foremost, I would like to thank all contributors of this project. I have been using Blender Nif Tools for quite some time now, and each iteration just gets better and better. 0.10.0 was a huge game-changer for me in regards to the embedded textures in .nif files as well as importing animations. What's more, I am now able to open all of the .nif files that I work with without the need of falling back to 2.49b

I would like to suggest adding the feature of exporting keyframe animation files (.kf) for Shin Megami Tensei: IMAGINE. The .nif tools currently are able to import .nif and .kf, and you are able to export your project as an FBX just fine. It'll even play all of the animations of your model. However, when it comes to exporting from an FBX that already has keyframe animation to a .nif file, it does not work due to the feature not being implemented.

Blender Nif Tools0.10.0 has greatly changed my workflow when it comes to content creation Megaten Imagine, and I plan to write documentation on 3D work for the game to make modeling more accessible for people who are interested. Attached are some errors that I got from my Blender Log.

If you need anything from me whether it be what I have experienced from using the Nif Tools or the files that I have been using during my testing, please do not hesitate to reach out; I would love to help in any way possible.

Attached is a nice little model of a character dancing. Enjoy! 💃 

https://mega.nz/file/jFpAnRyY#vZU3-a2nPY6e14bfFVQscwhJIKBCHc7U7N2KfrwD0jY

**Comment by HENDRIX-ZT2** [comment]
Submit some KF and NIF files samples. If import is possible already, enabling export should not be difficult.

**Comment by neomonkeus** [comment]
Yeah there is a download link there to megadownload, but would prefer if the assets were just attached to the ticket instead.

**Comment by HENDRIX-ZT2** [comment]
It links to an FBX file however, which is not what we need to test the plugin.

**Comment by TheRealHitoshura** [comment]
Thank you for looking into my request.

Attached are two demon files as well as a character model. The character's eyes will be black. Just use the eye texture instead to correct this. you may also have the adjust the Z axis on the eyes ever so slightly if you want the character to look forward.

Ayase: https://mega.nz/folder/3RgkQSYZ#5dX2-Idhh7SsdpDNkz0RYw

Michael: https://mega.nz/folder/fNZS0Lyb#xVmqFe8mGBm4AecEt4drfA

Satan: https://mega.nz/folder/uIwCUBaQ#RHkyycKJCxeRv4blBysA2w

Thank you again. If you would like more samples like male characters, npcs, etc. please let me know!
