### ISSUE TITLE
Merged Materials on Export  + Thank You!

### ISSUE THREAD

**Issue by TheRealHitoshura** [niftools/blender_niftools_addon#487]
Hello again! I just want to start by saying thank you for acknowledging my request last time. Version 0.12 has been even better than 0.10 for Megaten Imagine; export of animations works great!

However, it would seem that the merging of materials error still persists. Attached are some screenshots as well as the files I am working with. If there is already a known work around for this error, I can close this issue. Thank you again again for your hard work! If you need anything else from me, please let me know. ^v^

<img width="575" alt="Reference" src="https://user-images.githubusercontent.com/49658543/143283215-d4f7740e-68f8-4df5-98e5-ff772f964c69.png">

<img width="682" alt="MergedMaterials" src="https://user-images.githubusercontent.com/49658543/143283217-c0b674e6-af00-45f5-9000-3a2dccb3e07d.png">

<img width="835" alt="ViewInNifSkope" src="https://user-images.githubusercontent.com/49658543/143283218-3d4014d1-f3cf-4584-8daa-4f9be142b7da.png">

<img width="179" alt="Settings" src="https://user-images.githubusercontent.com/49658543/143283529-b54887e9-f9bd-408b-911f-206a7ac777f8.png">

[ZipZip.zip](https://github.com/niftools/blender_niftools_addon/files/7597635/ZipZip.zip)
.

**Comment by neomonkeus** [comment]
Can you retry with the `Optimize Materials` option delected. 
If that doesn't work, what is your expectation around deciding if a material is unique and shouldn't be merged.

**Comment by TheRealHitoshura** [comment]
Hiya! Thanks for the response.

I did and to no avail. I've tried a bunch of things like renaming the materials, unlinking the cloth model from the body. I've also tried changing the texture flag under the material for the Nif settings, but I still get the error.

Anything else I should try? I have also attached a Zip file at the end of my inquiry.

**Comment by TheRealHitoshura** [comment]
Issue solved. One Texture file it is.

**Comment by neomonkeus** [comment]
@TheRealHitoshura Then this is a duplicate of #374
