### ISSUE TITLE
"Some polygons of Parthurnax not assigned to any body part." error on unmodified model

### ISSUE THREAD

**Issue by XJDHDR** [niftools/blender_niftools_addon#496]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the issue template.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
I was attempting to modify the model for Paarthurnax (Skyrim LE version, not SE). When I exported my edited model, I encountered the following error:
```
Some polygons of Parthurnax not assigned to any body part.The unassigned polygons have been selected in the mesh so they can easily be identified.
D:\Users\<username removed>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py:692
```
The addon then selected a face (3 vertices) on the model's left wing (please see 2nd screenshot). The problem is that I hadn't touched those vertices or anything on the wing to begin with.

I then tried importing the original model into a new instance of Blender and then just export it without changing anything to see if the original model was working. I had the same error and the addon selected the same 3 vertices. The main question here is whether there is something wrong with the original model itself or is NifTools not importing or exporting it correctly.

### Blender Niftools Addon Version Info
Niftools Addon version: 0.0.13

### Blender Version Info
Blender version: 2.83.5

### Platform information
Windows 10 Pro x64 v20.04

## Steps to Reproduce

1. Extract a copy of Pathurnax.nif from the Skyrim LE Meshes BSA (Meshes\Actors\Dragon\Character Assets). Or use the attached copy.
2. Import it into Blender. I did not change any of the settings from their default. Or open the attached .blend file.
3. Export model as an NIF. I did not change any of the settings here either.

## Expected Result
The unedited model to be exported successfully.

## Actual Result
The error noted above appeared, the 3 vertices in question were selected and the NIF was not exported.

## Possible Fix
Can't think of anything.

## Screenshot
![image](https://user-images.githubusercontent.com/7355441/148138421-20dfe929-8735-444c-be75-2bd172ab8c0a.png)
![image](https://user-images.githubusercontent.com/7355441/148138407-1adb599e-a19d-4f39-9335-e4cc2065034d.png)

## Logs and Files
< No log files were created. >

### Info Bar Output
[Info bar output.txt](https://github.com/niftools/blender_niftools_addon/files/7811081/Info.bar.output.txt)

### Console Output
< The console was empty>

### Blend File
[Parthurnax-unmodified.zip](https://github.com/niftools/blender_niftools_addon/files/7811002/Parthurnax-unmodified.zip)

### Nif File
[parthurnax.zip](https://github.com/niftools/blender_niftools_addon/files/7810929/parthurnax.zip)

## Similar Known Issues
There are 2 other issues where the same error message appeared but they've already been fixed and I don't think they have the same cause: #284 and #444 

## Additional Information
These other dragon models I tried didn't have this problem. They could all be exported to new NIFs without issue:

- Alduin.nif
- BossDragon.nif
- Dragon.nif

I'm also using a PortableApps.com version of Blender downloaded from here, if that makes a difference: https://sourceforge.net/projects/portableapps/files/Blender%20Portable/

**Comment by neomonkeus** [comment]
Thanks for the issue report, its rare that we get the template filled in completely and correctly. 
This really helps with reproducing & troubleshooting.

**Comment by XJDHDR** [comment]
You're welcome. If there's anything else you need from me, do let me know.

**Comment by Candoran2** [comment]
Assigning the selected polygons to a body part seems to fix it, but I'll have to see whether it's a problem with the import or the model itself that causes this.

**Comment by SubhadeepG** [comment]
I checked parthurnax.nif and all vertices are in a body part. That means something is wrong with the import process.
