### ISSUE TITLE
.kf animations import on models messed up (fallout: new vegas)

### ISSUE THREAD

**Issue by AjStyles2** [niftools/blender_niftools_addon#503]
# Issue Overview
After importing .nif model of ghoul from Fallout: New Vegas everything imports fine, but importing .kf animations on skeleton seems wrong

### Blender Niftools Addon Version Info
0.0.13

### Blender Version Info
3.0.1

### Platform information
Windows 10 (64-bit)

## Context
No warnings or errors, but mesh is messed up after importing .kf animation

## Steps to Reproduce
1. Import a vanilla creature ghoul mesh with skeleton from Fallout: New Vegas with default preferences of importing .nif
2. After successful import of mesh, import .kf animation
3. Import is finished and animation is applied, but mesh is messed by this animation

## Expected Result
Original animation on skeleton on import .kf file after import .nif mesh

## Actual Result
Animation applies but with messing up mesh and not for all bones

## Screenshot
Importing .nif mesh including process everything and override scene information, scale correction 0.10 and geometry use custom normals (default settings in import)
![afterimportNIF](https://user-images.githubusercontent.com/71986423/159184759-9240a88c-e24a-4c1a-99f7-2ef829785855.jpg)

after import .kf anim file
![ghoulmessedupafteraniminport](https://user-images.githubusercontent.com/71986423/159184681-6cc15e01-f8b5-40da-9d94-2109e9cf0c5f.jpg)

## Logs and Files

[infolog.txt](https://github.com/niftools/blender_niftools_addon/files/8312158/infolog.txt)

### Info Bar Output
Finished.

### Console Output
[console-log.txt](https://github.com/niftools/blender_niftools_addon/files/8312161/console-log.txt)

### Blend File
[blend_file.zip](https://github.com/niftools/blender_niftools_addon/files/8312165/blend_file.zip)

### Nif File
[nif_and_kf_import.zip](https://github.com/niftools/blender_niftools_addon/files/8312168/nif_and_kf_import.zip)

## Additional Information
Also it happens with other creatures like securitrones or giantrats

**Comment by HENDRIX-ZT2** [comment]
Pretty sure that you have to import the skeleton nif first. Only that can be animated successfully, as the mesh itself has no bone hierarchy in its nodes.
