### ISSUE TITLE
Python errors importing and exporting

### ISSUE THREAD

**Issue by MindController** [niftools/blender_niftools_addon#511]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [x] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [x] Looking for support where the forums, chat or documentation is more appropriate.
 - [x] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

When I attempt to import a fallout 3 .nif file into blender using the niftools plugin, i'm immediately greeted with a slew of python code errors.  The model does get imported, but has no textures and it's a solid shiny black.  If I were to export the model, a whole other slew of errors pop up and it won't successfully export.  I have set the scene Fallout 3 and tried different import options, but nothing works.  I've even tried installing older versions of blender.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**

0.0.13

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**

Blender 3.0  But this also happens on the newest version of Blender.

### Platform information
**[Provide a brief overview of what OS your running on]**

Windows 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

When I attempt to import a fallout 3 .nif file into blender using the niftools plugin, i'm immediately greeted with a slew of python code errors.  The model does get imported, but has no textures and it's a solid shiny black.  If I were to export the model, a whole other slew of errors pop up and it won't successfully export.  I have set the scene Fallout 3 and tried different import options, but nothing works.  I've even tried installing older versions of blender.

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

1)  File > Import> NetImmerse/Gamebryo (.nif)
2)  Go to .nif file in fallout 3 data directory
3)  Get python errors

## Expected Result
**[Describe what you expected to have resulted from this process]**

No python errors with the model importing and exporting fine.

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**

Import a nif model and get tons of python errors and when I attempt to export, get more python errors and it won't export

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

![1](https://user-images.githubusercontent.com/596331/167832706-936e4e98-d6d9-42d4-bd29-ee4f81cb993f.png)
![2](https://user-images.githubusercontent.com/596331/167832710-7abf5bee-f86e-4ebf-870e-06d3b3c05e29.png)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by neomonkeus** [comment]
@MindController This issue has been resolved with the latest release.
