### ISSUE TITLE
Extract Embedded DDS Files, results in some working, while others have 0 byte of data, becomes pink textures.

### ISSUE THREAD

**Issue by NOXXiiTRiX** [niftools/blender_niftools_addon#517]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Hello, so I have tried to Extract Embedded DDS files in a game map. While extracting, i have found out that the map have pink textures.
![image](https://user-images.githubusercontent.com/104032131/170416615-a82b6d82-6dba-4be3-898a-1f4a2895c230.png)

Obviously, this is not the exact result i wanted. I wanted it to look like this in Nifskope.
![image](https://user-images.githubusercontent.com/104032131/170417456-0ea529bf-db96-48b7-9519-601429066d80.png)

For some reason, some of the smaller maps do work, like so. This is a different map of the same game.

As you can see, there are no pink textures.

![image](https://user-images.githubusercontent.com/104032131/170416832-a1642049-efbf-4cce-b65a-5582dccbf2e3.png)

-and it renders exactly just like in NifSkope.

![image](https://user-images.githubusercontent.com/104032131/170417000-52335996-fead-47a6-90be-87ea91edf14d.png)

Further investigating, i have researched that pink texture issues in Blender are cause by missing textures, and while investigating my
directory, it is true, i guess. Some embedded textures failed to extract without any bytes, like so. (For the first map.)

![image](https://user-images.githubusercontent.com/104032131/170417890-7b6149c7-71cb-4de7-bc39-6c0c4388d156.png)

This is how i imported the map into Blender. 
![image](https://user-images.githubusercontent.com/104032131/170418050-c0662fc2-78e0-4ba9-bc1a-3623e4f9acac.png)

And after finished, it will result in some textures having zero bytes of data, equals to pink textures.

### Blender Niftools Addon Version Info
**[blender_niftools_addon-v0.0.14-2022-05-21-0f0e35a]**

### Blender Version Info
**[blender-3.1.2-windows-x64]**

### Platform information
**[Windows 10 Pro]**

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

## Expected Result
**[Describe what you expected to have resulted from this process]**

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
[output.txt](https://github.com/niftools/blender_niftools_addon/files/8777801/output.txt)

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
https://www32.zippyshare.com/v/XqgDwjzI/file.html

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[The second map was small, so extract DDS files was up to 400+, while the first map was aroud 999+]**

**Comment by HENDRIX-ZT2** [comment]
![grafik](https://user-images.githubusercontent.com/28632661/170461298-4bc527b7-4c35-450e-9df5-ab173b5e4ad0.png)

Several issues here:
- a lot of re-used textures, slowing down import
- exceeds limit of master, already solved
- unsupported pixel format FMT_RGB

**Comment by HENDRIX-ZT2** [comment]
WARNING | Pixel format not supported in embedded texture C:\Users\arnfi\Desktop\Coding\NIF\internal textures\TDM_LostTemple - Copy\MAP_18_LightMap_01.tga!
Traceback (most recent call last):
  File "C:\Users\arnfi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\loader.py", line 223, in import_embedded_texture_source
    source.pixel_data.save_as_dds(stream)
  File "C:\Users\arnfi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\loader.py", line 117, in save_as_dds_override
    pixeldata.set_value(self.__get_pixeldata_stream())
  File "C:\Users\arnfi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\common.py", line 701, in set_value
    raise ValueError('data too long')
ValueError: data too long

**Comment by NOXXiiTRiX** [comment]
> ![grafik](https://user-images.githubusercontent.com/28632661/170461298-4bc527b7-4c35-450e-9df5-ab173b5e4ad0.png)
> 
> Several issues here:
> 
> * a lot of re-used textures, slowing down import
> * exceeds limit of master, already solved
> * unsupported pixel format FMT_RGB

This is really good! How did ya made this result?
