### ISSUE TITLE
Unable to Import 

### ISSUE THREAD

**Issue by CrazyCanadian121** [niftools/blender_niftools_addon#531]
whenever I attempt to import a .NIF file it ends up only Importing a single piece of the model and outputting a massive error. When I set the game engine to the proper type it just ends up switching back to Dark Age of Camelot. 
I'm using Blender V3.0 and the latest version of this plugin.
on a side note, it's probably an easy fix that I'm missing but it's 4:00 am my time and my brain is not working so I do appologize
![image](https://user-images.githubusercontent.com/106294147/187385117-9bde6f35-14ef-467c-af82-9a4cfdef7251.png)

**Comment by Candoran2** [comment]
Could you attach the nif file you're trying to import?

**Comment by Candoran2** [comment]
No response for a year, closed as stale. If you believe this is in error, please attach the requested information and it may be reopened.
