### ISSUE TITLE
Unable to import skeleton.nif due to enum error

### ISSUE THREAD

**Issue by derickso** [niftools/blender_niftools_addon#532]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Receive error when trying to import a skeleton.nif

### Blender Niftools Addon Version Info
v0.0.14

### Blender Version Info
2.83

### Platform information
Windows 11

## Context
Importing skeleton.nif for use with animation.kf

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Import skeleton.nif
2. Receive error message

## Expected Result
Skeleton is imported properly

## Actual Result
File "C:\..Blender Foundation\Blender\2.83\scripts\addons\io_scene_niftools\modules\nif_import\collision\havok.py", line 206, in _import_bhk_rigid_body b_col_obj.nifcollision.collision_layer = str(bhkshape.layer)
TypeError: bpy_Struct: item.attr = val: enum "1" not found in ()

## Screenshot
[**[If relevant, include a screenshot]**](https://i.imgur.com/IqLlANH.png)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
Could you attach the nif?

**Comment by Candoran2** [comment]
No response for over a year, closed as stale. If you believe this is in error, please attach the requested information and it may be reopened.
