### ISSUE TITLE
What to do with the error "Python: Traceback (last call)" / "ValueError: Unknown block type BSDynamicTriShape?"

### ISSUE THREAD

**Issue by woobid** [niftools/blender_niftools_addon#533]
Hi, can you please tell me why the following error occurs:

[Screen
![6zbtHoBmXBF-VyBD8qo6B-dsGhJNBlG9ZQqKw_rigZ109Tqv-CGm1ZFgYwenb8wYz1CVvqTEoHIGuNlVcKT_c7CK](https://user-images.githubusercontent.com/53191922/188328404-f05fbffb-6c61-4f4b-9dc1-f06b0876aa3c.jpg)
](https://sun9-east.userapi.com/sun9-23/s/v1/ig2/6zbtHoBmXBF-VyBD8qo6B-dsGhJNBlG9ZQqKw_rigZ109Tqv-CGm1ZFgYwenb8wYz1CVvqTEoHIGuNlVcKT_c7CK.jpg?size=915x448&quality=96&type=album)

The code is messy, because I scanned it from a picture, because it is not copied from the window (the idea for the backlog), I had to rewrite by hand.

`Report: Error`

`Python: Traceback (most recent call last)`

`File "CAUsers\kiriAppData\Roaming\Blender ``Foundation\Blender\3.2\scriptsladdonstio_scene_niftools\dependencies\pyffvormats\nif\_init_py", line 1375, in read`
`block = getattr(NifFormat, block type)()`

`Attributetror: type object 'NifFormat has no attribute 'BSDynamicTriShape’`

`During handling ofthe above exception, another exception occurred:`

`‘Traceback (most recent cal last}`

`File "CAUsers\KiriNAppData\Roaming\Blender Foundation\Blender\3.2\scripts\addonst\io_scene_niftools\operators\nif_import op.py", line 127, in execute`
`return Niflmport(self,context).executel)`

`File "CAUsers\kiriNAppData\Roaming\Blender Foundation\Blender\3.2\scripts\addonst\io_ scene_niftools\nif_importpy" line 75, in ``execute`
`self.oad_fles|) # needs to be first to provide version info`

`File "CAUsers\KiriAppData\Roaming\Blender Foundationi\Blender\3.2\scripts\addonst\io_scene_niftools\nif import py", line 141, in `load files`
`NifData init(NiFile load niftNifOp props.filepath))`

`File "CAUsers\KiriNAppData\Roaming|Blender Foundation\Blender\3.2\scripts\addonstio_ scene_niftools\file_io\nif.py", line 64, in load nif`
`data.read{nif stream)`

`File "CAUsers\KiriNAppData\Roaming\Blender Foundation\Blender\3.2\scripts\addonstio_ ``scene_niftools\dependencies\pyffi\formats\nif\_init_.py", line 1377, in read`
`raise Valuetrror(`
`ValueError: Unknown block type `BSDynamicTriShape``

Blender version = 3.2.2. , version of niftools =0.0.14, platform = Windows 10

The steps I have done: Via BSA Browser I exported Skyrim game nif files. Then in Blender selected the game: Skyrim and made import through the plugin niftools and got this error.

How to work with this error?

**Comment by ionhsmith** [comment]
Im getting this same error

**Comment by L0FKA** [comment]
Look at last line, clearly you have unsupported version of a nif file wich may have wrong header structure, validate that you can open it in NifSkope, also would be nice to have this file for debugging at least to say it in error message that "We can't process this file, unsupported nif version {version}" 😌

**Comment by Candoran2** [comment]
This is because SSE nifs are not supported. See also #474. For right now, you can convert them to LE nifs with SSE Nif Optimizer or similar software.

**Comment by ionhsmith** [comment]
Candoran2... Looks like your right....  so what are all the modders doing to get the nif files from SSE into blender? Seeing as it seems SSE is the way alot of people are going for modding

**Comment by Candoran2** [comment]
> Candoran2... Looks like your right.... so what are all the modders doing to get the nif files from SSE into blender? Seeing as it seems SSE is the way alot of people are going for modding

Exactly what I said in the comment: "For right now, you can convert them to LE nifs with SSE Nif Optimizer or similar software." (and of course, you can import LE nifs).

**Comment by woobid** [comment]
> Это связано с тем, что SSE nifs не встречается. См. также #474 . На данный момент вы можете преобразовать их в LE nif с помощью SSE Nif Optimizer или аналогичного программного обеспечения.

Thank you, friend!

**Comment by Candoran2** [comment]
SSE meshes are now supported (import only, for now). That resolves this error.
