### ISSUE TITLE
ValueError: Nif version 30.2.0.3 not supported.

### ISSUE THREAD

**Issue by hanxiaoxin778** [niftools/blender_niftools_addon#534]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Receive error when trying to import a skeleton.nif

### Blender Niftools Addon Version Info
v0.0.14

### Blender Version Info
v3.2.2

### Platform information
Windows 10

## Context
Importing nif

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. Import skeleton.nif
 #. Receive error message

## Expected Result
Skeleton is imported properly

## Actual Result
`Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 127, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_scene_niftools\nif_import.py", line 75, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_scene_niftools\nif_import.py", line 141, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_scene_niftools\file_io\nif.py", line 59, in load_nif
    data.inspect_version_only(nif_stream)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1197, in inspect_version_only
    raise ValueError("Nif version %s not supported." % version_str)
ValueError: Nif version 30.2.0.3 not supported.`

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
[f_body.zip](https://github.com/niftools/blender_niftools_addon/files/9492235/f_body.zip)

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
Fixed in [release 0.1.0](https://github.com/niftools/blender_niftools_addon/releases/tag/v0.1.0)
