### ISSUE TITLE
Python reports missing file path enabling plugin in Blender 3.3

### ISSUE THREAD

**Issue by sna-scourtney** [niftools/blender_niftools_addon#539]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

### Blender Niftools Addon Version Info
0.0.14 (reproduced attempting to revert to 0.0.13 as well)

### Blender Version Info
Blender version 3.3.0

### Platform information
Windows 10 64-bit

## Context
I had previously installed Niftools in Blender 2.8.x and was able to keep it running up to and including Blender 3.3.0, but on attempting to update from 0.0.13 to 0.0.14 the installation works but enabling the plugin throws a python error.

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #.  Remove any previous version of Blender Niftools.
 #.  Install 0.0.13 or 0.0.14 from the Blender Preferences dialog.
 #.  Restart Blender as instructed.
 #.  Return to the Preferences dialog and attempt to enable the plugin via its checkbox.

## Expected Result
io_scene_niftools enabled and functioning

## Actual Result
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 432, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 287, in enable
    if mod and os.path.exists(mod.__file__):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**
I'm investigating this myself in hopes of contributing a code patch but don't have a solution yet.

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**
As a diagnostic, I tried enabling the plugin from the Python console:

>>> import addon_utils
>>> print(addon_utils.check("io_scene_niftools"))
Warning: addon-module io_scene_niftools found module but without '__addon_enabled__' field, possible name collision from file: None
(False, False)

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup\bl_operators\userpref.py", line 432, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 287, in enable
    if mod and os.path.exists(mod.__file__):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Blend File
n/a

### Nif File
n/a

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
I cloned the source and will continue looking for the problem but wanted to get the info captured while it's fresh. If it would be helpful, I also have a source build tree of the latest Blender alpha where I could do further testing once we think we have a solution for 3.3.

**Comment by Allofich** [comment]
I was just able to install and enable the v0.014 plugin on the latest Blender the other day.

Specifically I have Blender version "3.3.1", as gotten from the "Download Blender 3.3.1 LTS" button on the homepage at https://www.blender.org/download/. Is it the same as what you are using?

**Comment by Candoran2** [comment]
No response for a year, closed as stale. If you believe this is in error, please attach the requested information and it may be reopened.
