### ISSUE TITLE
Exported .NIF files crash Oblivion (can be repaired using NifSkope)

### ISSUE THREAD

**Issue by Allofich** [niftools/blender_niftools_addon#545]
# Issue Overview
With the latest available code, after importing and exporting one of the .nif files that comes with Oblivion and then attempting to use the exported .nif in-game, Oblivion will crash. If "sanitized" with NIFSkope, it longer crashes.

### Blender Niftools Addon Version Info
Built the addon using the following:
Python 3.11
New Pyffi: https://github.com/Candoran2/new-pyffi/commit/c8508fe316aa2e978e7677308f06f1b6a2ff48e4
New nif xml: https://github.com/niftools/nifxml/commit/89d03ffe69254ef4b3b58b0a22ec2ff9820b2e63
Latest blender addon code at: https://github.com/Candoran2/blender_nif_plugin/commit/f3898fe667b214367569c5be761bbcf49b527eea
(code up for PR in https://github.com/niftools/blender_niftools_addon/pull/541)

### Blender Version Info
3.4

### Platform information
Windows 11 22H2

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Build the latest blender_niftools_addon using the code versions listed above.
2. Import `meshes/architecture/anvil/anvilaltar01.nif` from Oblivion into Blender. This file can be obtained by extracting it from `data/Oblivion - Meshes.bsa` with a BSA extracting program.
3. Set the imported .nif file's game parameter to `Oblivion` (otherwise it will not be exported) and then export it.
4. Put the exported file in your Oblivion game directory under `Data/meshes/architecture/anvil/anvilaltar01.nif` to override the default model.
5. I believe that in order for the default model to be used, the .nif file needs to have a later date than the `data/Oblivion - Meshes.bsa` file (or you can use "archive invalidation" I think?)
6. Go to an area in-game that uses the model. You can do so by opening the console and typing "coc anvilbenirusmanorbasement".
7. Observe that the game crashes while loading the area.
8. Open the .NIF with NifSkope 2.0 Dev 7 and save it with the option to auto-sanitize on save checked.
9. Do step 6 again and observe that no crash happens.
## Expected Result
Importing a working .nif and exporting it without making any changes to it should create a working .nif that does not crash the game.

## Actual Result
Exported .nif crashes.

### Console Output
There are at least 2 versions of this file, one is included with the Oblivion releases on Steam and GOG. The other is from the Oblivion release on DVD.

The following warnings appear during export of the both versions of the file.

```
niftools:INFO:Writing .nif file
WARNING:root:instance 1 is not a member of the <enum 'OblivionLayer'> class
WARNING:root:instance 1 is not a member of the <enum 'hkResponseType'> class
WARNING:root:instance 1 is not a member of the <enum 'OblivionLayer'> class
WARNING:root:instance 1 is not a member of the <enum 'hkResponseType'> class
WARNING:root:instance 1 is not a member of the <enum 'SpecularFlags'> class
```

An additional warning and error appear with the DVD version of the file on import and export, but since the Steam/GOG version without those also crashes, I am omitting them.

### Nif File
These are the exported NIFs that crash the game (no sanitation from NifSkope applied)
[anvilaltarNIFs.zip](https://github.com/niftools/blender_niftools_addon/files/10253288/anvilaltarNIFs.zip)

**Comment by Candoran2** [comment]
Can you replicate the fix with any specific single NifSkope sanitization spell?

**Comment by Allofich** [comment]
Testing them now.

**Comment by Allofich** [comment]
It's the "Collapse Link Arrays" spell that fixes them.

**Comment by Allofich** [comment]
Confirmed fixed by the above commit. Neither of the exported .nif files crash the game now.
