### ISSUE TITLE
ValueError: too many values to unpack (expected 2) for original Oblivion .nifs

### ISSUE THREAD

**Issue by Allofich** [niftools/blender_niftools_addon#550]
# Issue Overview
Some .nif files that come with Oblivion have a "ValueError: too many values to unpack (expected 2)" error on import.

### Blender Niftools Addon Version Info
Built the addon using the following:
Python 3.11
New Pyffi: https://github.com/Candoran2/new-pyffi/commit/6d113fdcfcf950eae138f7e75efcc6b057c1d605
New nif xml: https://github.com/Candoran2/nifxml/commit/d0ab9271e2c2bf75eacb46082b93e1d304b551e6
Latest blender addon code at: https://github.com/Candoran2/blender_nif_plugin/commit/cc4012830897ed32c378c3a2e5335e68d7ef3d48

### Blender Version Info
3.4

### Platform information
Windows 11 22H2

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Build the latest blender_niftools_addon using the code versions listed above.
2. Import the problem mesh from Oblivion (below) into Blender.
3. The file is imported but has an error.
## Expected Result
Should import without errors.

## Actual Result
Imports with an error.

### Console Output
```
niftools:INFO:Importing mesh data for geometry 'GenericBottle01:0'
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 160, in import_root
    ObjectProperty().import_extra_datas(root_block, b_obj)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\property\object\__init__.py", line 73, in import_extra_datas
    for k, v in game_map:
ValueError: too many values to unpack (expected 2)
```
### Nif File
I found this error while testing the .nifs in the `meshes/idleobjects` folder.

`alchemyretort.nif`
`ascensionparticles.nif`
`dogfood.nif`
`genericbottle.nif`
`genericmug.nif`
`genericpotion.nif`
`paintbrush.nif`
all show the error.

`alchemybottle.nif`
`breadpiece.nif`
`genericbook.nif`
`pallete.nif`
do not.

Comparing `genericpotion.nif` and `alchemybottle.nif` in NifSkope, the only differences I saw were in Header String, Version, User Version, User Version2, the presence of EndianType in `alchemybottle.nif`, and differences in two NiStringExtraData values.
![1](https://user-images.githubusercontent.com/19624336/208684595-a9b0c686-e248-44f8-85f6-2d4fbd4ac4fe.png)
![2](https://user-images.githubusercontent.com/19624336/208685278-bacbfd00-744c-4395-aaf4-dd1d06cdddfc.png)

[idleobjects.zip](https://github.com/niftools/blender_niftools_addon/files/10269025/idleobjects.zip)

**Comment by Candoran2** [comment]
The actual error here is simple to fix - although doing so does reveal a not-so-simple other problem, which has caused me to reconsider how the Prn values are done.

**Comment by Allofich** [comment]
I can confirm that all the .nifs I listed above with the error, as well as some others I found, are fixed with the new code.
Since I only opened this for the error message I would be OK with closing this issue, but I'll leave it open since you described the new code as a partial fix resulting in wrong values.

**Comment by Candoran2** [comment]
It was completely fixed by the subsequent commit, so I think closing the issue would be fine.
