### ISSUE TITLE
Vertex order is not preserved on export.

### ISSUE THREAD

**Issue by ja231c** [niftools/blender_niftools_addon#554]
# Issue Overview
Vertex order is not preserved on export.

## Context
For Bethesda games, .tri files depend on the vertex order, the _0 and _1 outfit meshes do too, bodyslide files also do, basically, it's annoying to have it not be preserved.

## Steps to Reproduce
Export file, observe the changed vertex order.

## Expected Result
The vertex order stays exactly the same as it was in Blender.

## Actual Result
The vertex order changes.

**Comment by Candoran2** [comment]
1. Do you know if this also happens if you set the precision level to 0.0?
2. Could you provide example nifs/blend files?
3. Is this with nifs that you imported, maybe edited and subsequently exported, or are you talking about nifs that you created from scratch in Blender?

**Comment by ja231c** [comment]
1. By precision you mean the Epsilon Dev Option, correct? And yes, it does.
2. Just add a random primitive and export that, it happens with everything, even a Plane has a different vertex order in the exported NIF.
3. Import works properly, imported vertex order is exactly the same as NIF (as it should be), it's export that reorders it.

**Comment by Candoran2** [comment]
What is probably responsible for the changed order of the vertices is the way we get them (iterate through every polygon rather through just the bare list of vertices). Not sure that can be changed. However, we do keep a list that maps Blender vertices to its nif equivalent, so that could be used after getting those vertices to sort them back.

**Comment by HENDRIX-ZT2** [comment]
> What is probably responsible for the changed order of the vertices is the way we get them (iterate through every polygon rather through just the bare list of vertices). Not sure that can be changed. However, we do keep a list that maps Blender vertices to its nif equivalent, so that could be used after getting those vertices to sort them back.

If the order is important, we could just prepend a dict mapping to restore the sorting into blender order. But I don't think maintaining order is doable when duplicates on uv seams have been removed.
