### ISSUE TITLE
Why would you call a Skyrim plugin a general name like "NIF" and misleading folks - I had to try it & google its bug to found out!

### ISSUE THREAD

**Issue by 4Brad-23** [niftools/blender_niftools_addon#560]
If you're not willing to change the title then at least make a proper description and even so it's misleading.

**Comment by Candoran2** [comment]
The plugin supports nif formats used by a number of games, including but not limited to Skyrim. Many games have their own specific version, adaptation or custom blocks. If there is a specific game you would like support for that isn't supported yet, you can make a separate issue for that (as long as it isn't already an existing issue).
