### ISSUE TITLE
Batch convert

### ISSUE THREAD

**Issue by Techttv** [niftools/blender_niftools_addon#561]
Until the latest version, it wasn't possible to export Epic Mickey 2. But now that's supported, I need to convert a lot of files and I can't do it one by one.

It would be great if you could make an example script to run inside blender. I already tried to make it by myself but I can't understand what functions I need to use and they're parameters.

Or you could do an external script so you don't need to open blender, but I don't know if it's possibile.

**Comment by HENDRIX-ZT2** [comment]
We're not condoning or supporting asset ripping, so you will have to figure that out on your own.
