### ISSUE TITLE
 Incomplete plugin import

### ISSUE THREAD

**Issue by hsl9999** [niftools/blender_niftools_addon#566]
Blender Niftools Addon Version Info
0.0.14

Blender Version Info
2.9.3.16

Platform information
Windows 10 x64 latest

Context
When importing nif, only bones can be seen, and NiMesh is not imported normally

Expected Result
The plugin works fine

Screenshot
https://drive.google.com/file/d/1a5B2wBf7arFoGtGajJ2a26_WCKaoVWlQ/view?usp=sharing

Nif File
https://drive.google.com/file/d/1FklEJpFoS6VZLBvuF8JMzYko760VSCGO/view?usp=sharing

**Comment by Candoran2** [comment]
Could you specify which game this nif is from?

**Comment by hsl9999** [comment]
> 


It's a game called Archlord 2

**Comment by hsl9999** [comment]
I found the file format is "Gamebryo File Format, Version 20.6.0.0"

**Comment by Kendaman** [comment]
![nif](https://github.com/niftools/blender_niftools_addon/assets/48504101/e652a385-dbbf-45ed-a118-e0ef58641b1d)
I would like to look into this a little more, but I can't unzip the dat for this game. The decompression tool has already disappeared from the server. need extractor.

**Comment by hsl9999** [comment]
> ![nif](https://user-images.githubusercontent.com/48504101/238499880-e652a385-dbbf-45ed-a118-e0ef58641b1d.PNG) I would like to look into this a little more, but I can't unzip the dat for this game. The decompression tool has already disappeared from the server. need extractor.

Hello, may I ask if this is max or blender? Which version can read it? I hope to make some mods for this game.Thanks.

**Comment by hsl9999** [comment]
Can this problem be solved？@Candoran2  @neomonkeus

**Comment by Candoran2** [comment]
Yes. With the most recent code changes to the plugin you can import it and get a (somewhat-working) nif.
![image](https://github.com/niftools/blender_niftools_addon/assets/45334438/002437fd-7e52-4c92-a126-19e3d0f38f98)
However, that isn't released yet. If you have a bit of know-how you can create the updated version of the plugin yourself based on the publicly available repos, but otherwise you'll have to wait for a new release. Most small kinks with the large update we've been working on have been worked out, so that should be not _too_ far in the future.

**Comment by hsl9999** [comment]
> Yes. With the most recent code changes to the plugin you can import it and get a (somewhat-working) nif. ![image](https://user-images.githubusercontent.com/45334438/238957020-002437fd-7e52-4c92-a126-19e3d0f38f98.png) However, that isn't released yet. If you have a bit of know-how you can create the updated version of the plugin yourself based on the publicly available repos, but otherwise you'll have to wait for a new release. Most small kinks with the large update we've been working on have been worked out, so that should be not _too_ far in the future.


Thank you very much, I will try to compile the plugin myself

**Comment by Kendaman** [comment]
Is it possible to import kf in the latest version of the plugin? For this game, NiSequenceData is used.

**Comment by hsl9999** [comment]
The problem with the trunk is still there, can you add a modified branch? I'll try it myself, thanks. @Candoran2

**Comment by Candoran2** [comment]
Steps to use cobra-tools to create the `generated` module necessary for the blender niftools addon:
- Clone OpenNaja/cobra-tools.
- Clone Candoran2/nifxml (branch mickeychanges)
- Clone Candoran2/new-pyffi
- Create a symbolic link to `nifxml/nif.xml` in `new-pyffi/formats/nif`
- Create a symbolic link to `new-pyffi/formats/nif` in `cobra-tools/source/formats`
- Create a symbolic link to `new-pyffi/spells` in `cobra-tools/source`
- Create a symbolic link to `new-pyffi/utils` in `cobra-tools/source`
- Run codegen.py from cobra-tools.
- Replace makezip.bat with the one attached here.
- Set the `GENERATED_FOLDER` variable to point to the cobra-tools/generated folder.
- Run install.bat
It's quite a bit of setup, but you only need to do it once (except for running install.bat or setting `GENERATED_FOLDER`).

[makezip.zip](https://github.com/niftools/blender_niftools_addon/files/11589895/makezip.zip)

My most recent changes are available on https://github.com/Candoran2/blender_nif_plugin/tree/pyffi_overhaul, but they'll be pulled into this repository in due time as well. Same goes for my nifxml changes.

**Comment by svip** [comment]
Hey @Candoran2, I recognise this issue is closed, but I felt it might be a bit much to create another issue.  When I follow the above steps (though modify `makezip.sh` to include `cp -r "$GENERATED_FOLDER" "${DEPS_OUT:-${BUILD_DIR}/dependencies}/generated"`), I get these errors during cobra-tools' `codegen.py`:

```  File "[...]/cobra-tools/codegen/Compound.py", line 102, in read
    condition = union.write_filtered_attributes(f, condition, target_variable="instance")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/cobra-tools/codegen/Union.py", line 309, in write_filtered_attributes
    raise AttributeError(
AttributeError: Default tag without or with overlapping conditionals on type  FORCE_BOMB
```

Which may be resulting in the somewhat unusual final line to `NiAVObject.py`:
```		if instance.context.bs_header.bs_version > 26:```
(Yes, that's the final line.)

If you prefer me putting this issue somewhere else, let me know.
