### ISSUE TITLE
Addon cannot be enabled

### ISSUE THREAD

**Issue by RMD-Angel** [niftools/blender_niftools_addon#567]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Addon installs from .zip file, but cannot be enabled.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
0.0.14

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
2.79

### Platform information
**[Provide a brief overview of what OS your running on]**
Windows 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
I downloaded the latest version of the addon as a zip file, made Blender installed it, then clicked the checkbox, only to receive an error message.

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 
Download Addon as zip file, then clicked the checkbox to enable.

## Expected Result
**[Describe what you expected to have resulted from this process]**
The addon is enabled.

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
Traceback (most recent call last):
	File "C:\Users\(username)\Downloads\blender-2.79-windows64\2.79\scripts\modules\addon_utils.py", line 331, in enable mod = __import__(module_name)
	File "C:\Users\(username)\Appdata\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_scene-niftools\__init__.py", line 74 NifLog.info(f"Loading: Blender Niftools Addon: {version.read()}")

SyntaxError: invalid syntax

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
Addon version 0.0.14 is only compatible with Blender 2.8 or later (and we recommend you use the latest version of  Blender if you can). The last released version compatible with 2.79 is found here: https://github.com/niftools/blender_niftools_addon/releases/tag/blender-2.6.0a.dev6

**Comment by Candoran2** [comment]
Blender version compatibility problem.

**Comment by RMD-Angel** [comment]
Thank you
