### ISSUE TITLE
Digimon Masters - Missing Face 

### ISSUE THREAD

**Issue by zeak6464** [niftools/blender_niftools_addon#574]
In NifScope it looks like this ![Screenshot 2023-06-05 113939](https://github.com/niftools/blender_niftools_addon/assets/2738141/f7710619-8fc6-4f4a-a5a6-1980374fcd0e)
 
 In Blender when importing it looks like this. 
![image](https://github.com/niftools/blender_niftools_addon/assets/2738141/640c962c-77ce-403d-af46-2727748b0334)
[0075024_chackmonl.zip](https://github.com/niftools/blender_niftools_addon/files/11654304/0075024_chackmonl.zip)

Blender throws me this error. AttributeError: 'NoneType' object has no attribute 'data'

**Comment by Candoran2** [comment]
Are the files you posted unaltered from the game? Block 140 appears to be a NiFloatInterpolator without a linked block in the `Data` field.
![image](https://github.com/niftools/blender_niftools_addon/assets/45334438/2f207676-2888-4008-93ee-0a27b41d3eed)
Adding one seems to solve the error and allow for import of the full geometry:
![image](https://github.com/niftools/blender_niftools_addon/assets/45334438/f7b09d00-429b-4474-8e3d-3622a8cf2363)
