### ISSUE TITLE
Mesh is not split on mirrored UVs

### ISSUE THREAD

**Issue by ja231c** [niftools/blender_niftools_addon#586]
# Issue Overview
As tangents and bitangents are per-vertex and UV-relative and there is only one vertex and tangents and/or bitangents need to go in different directions when UVs are mirrored since the UV goes in a different direction.

### Blender Niftools Addon Version Info
0.0.15 from commit 67e0f92158c7135d0e7095b07ee1dc81f0c4a205

### Blender Version Info
3.5.0

### Platform information
Windows 10

## Context
Mirrored UVs are a great way to reduce texture size without affecting texel density.
NiTriShapeData/BSTriShape stores only one tangent and bitangent per vertex.

## Steps to Reproduce
Export mesh with mirrored UVs.

## Expected Result
Vertexes get split where the UV is mirrored.

## Actual Result
There is only on vertex on the mirror, which has tangents and/or bitangents that are not correct

## Possible Fix
Split mesh where this happens.

## Screenshot
Expected Result (note the lack of line)
![good_small](https://github.com/niftools/blender_niftools_addon/assets/68137237/534188b4-bf47-4e40-a5cd-b20dac2b1089)
Current Result (note the line)
![bad_small](https://github.com/niftools/blender_niftools_addon/assets/68137237/560eaece-c1d8-4e6b-a801-d7f1e1870db9)

### Blend File
[Blend.zip](https://github.com/niftools/blender_niftools_addon/files/11941840/Blend.zip)

### Nif File
[NIFs.zip](https://github.com/niftools/blender_niftools_addon/files/11941812/NIFs.zip)

**Comment by Candoran2** [comment]
I don't expect there to be a difference, since we didn't make any changes to tangents/bitangent export. However, have you tried v0.1.0 instead of 0.0.15?

**Comment by HENDRIX-ZT2** [comment]
I believe bitangents have never been involved in the splitting code. Not sure though. Yes, when a mesh stores bitangents, they need to be taken into consideration for duplicating vertices.
