### ISSUE TITLE
I encountered a problem exporting 'nif'. May I know how to resolve it.

### ISSUE THREAD

**Issue by mirkiss** [niftools/blender_niftools_addon#589]
I encountered a problem exporting 'nif'. May I know how to resolve it.
---------------------------------------------------------------------------------------------------------------------------------

Python: Traceback (most recent call last):
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_export.py", line 131, in execute
    self.version, data = scene.get_version_data()
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\scene\__init__.py", line 53, in get_version_data
    user_version = b_scene.user_version if b_scene.user_version else b_scene.USER_VERSION.get(game, 0)
AttributeError: 'Scene' object has no attribute 'USER_VERSION'
---------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_niftools\nif_export.py", line 131, in execute
    self.version, data = scene.get_version_data()
  File "C:\Users\Guenter\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\io_scene_niftools\modules\nif_export\scene\__init__.py", line 53, in get_version_data
    user_version = b_scene.user_version if b_scene.user_version else b_scene.USER_VERSION.get(game, 0)
AttributeError: 'Scene' object has no attribute 'USER_VERSION'

location: <unknown location>:-1

---------------------------------------------------------------------------------------------------------------------------------

Blender 3.6 and 2.83.20
Python 3.11.2
nif file Version 20.3.0.9

@niftools/blender-niftools-addon-reviewer -

**Comment by Chibgy** [comment]
Same error is persistent with me

Blender 3.5 and 2.90.0
Python 3.10.10
nif file version 20.1.0.3

**Comment by Chibgy** [comment]
for some reason removing textures fixes this exporting error for me, don't know if its related.

**Comment by mirkiss** [comment]
Try starting Blender in administrator mode

**Comment by Chibgy** [comment]
> Try starting Blender in administrator mode

the error still appeared in administrator mode

**Comment by Candoran2** [comment]
Could you post the .blend file you are trying to export the nif from, as per the template?

**Comment by Chibgy** [comment]
> Could you post the .blend file you are trying to export the nif from, as per the template?

[idle1.zip](https://github.com/niftools/blender_niftools_addon/files/12134386/idle1.zip)

**Comment by jameswilddev** [comment]
I'm seeing this too, please let me know if there's anything I can provide to help.

**Comment by jameswilddev** [comment]
It doesn't appear to be specific to any particular Blender version, I am able to reproduce the issue both on the most recent 3.6 and the oldest supported 2.82.

**Comment by Candoran2** [comment]
> I'm seeing this too, please let me know if there's anything I can provide to help.

I think we've got a fix for this already, but it would need to be pulled into the main repository and a release would have to be created.

**Comment by mirkiss** [comment]
> 您能否按照模板发布您尝试从中导出 nif 的 .blend 文件？

Blender 3.6 and 2.83.20
Python 3.11.2
nif file Version 20.3.0.9

Gamebryo version 2.3. The nif version exported with 3dmax9 is 20.3.0.9, which I have been using all along. However, it seems that there may be some issues with opening and exporting the plugin.


Here is my nif file   @Candoran2 
[fs_chuanshuo6.zip](https://github.com/niftools/blender_niftools_addon/files/12370807/fs_chuanshuo6.zip)

**Comment by Candoran2** [comment]
> But there is a new issue. When importing, the prompt "Game set to 'Games. BULLY_SE', but multiple games qualified" will be displayed. Is this affected? @Candoran2

That message is a simple warning message and should not affect the import process significantly.
