### ISSUE TITLE
export unable to recognize my dds images

### ISSUE THREAD

**Issue by Chibgy** [niftools/blender_niftools_addon#590]
Do not know how to export texture node 'Image Texture' in material 'mat_dvl_mdl_sonic' with label 'tex_sonic_body.dds'.Delete it or change its label.
C:\Users\joey7\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_scene_niftools\modules\nif_export\property\texture\__init__.py:186

Blender 3.5 and 2.90.0
Python 3.10.10
nif file version 20.1.0.3

[idle1.zip](https://github.com/niftools/blender_niftools_addon/files/12134639/idle1.zip)

**Comment by Candoran2** [comment]
Have you tried changing the label of the texture in question? For example, for the base color texture, the texture node should be named 'Base', whereas the normal texture node should be named 'Normal'. [This article](https://wiki.beyondskyrim.org/wiki/Arcane_University:Blender_2.8%2B_Export#Shaders) (though written for Skyrim), shows an example of that.

**Comment by Chibgy** [comment]
🤦‍♂️ that was the exact issue, I imported these from another game and just didnt know that those nodes where what it was talking about for the labels. sorry for wasting your time.
