### ISSUE TITLE
Vertex color data not importing from BSTriShapes

### ISSUE THREAD

**Issue by LarryBoi** [niftools/blender_niftools_addon#599]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

Imported meshes from Skyrim Special Edition don't contain any vertex color data in Color Attributes, and show up as completely white in Blender

## Version Information
Blender version - 3.6.1

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
Niftools version - latest

### Blender Version Info
Blender version - 3.6.1

### Platform information
Windows

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

## Expected Result
Imported BSTriShape nodes should contain vertex color data

## Actual Result
Imported BSTriShape nodes show no vertex color data

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
Attached are images of mountaincliff01.nif from both Skyrim SE and Skyrim LE showcasing the issue
![image](https://github.com/niftools/blender_niftools_addon/assets/68171930/b588abbc-15f3-42aa-ac08-2fc89d7d70fa)
![image](https://github.com/niftools/blender_niftools_addon/assets/68171930/512fcf1e-07d5-4032-9dd1-cf965d0af955)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
Attached nifs
[mountaincliffnifs.zip](https://github.com/niftools/blender_niftools_addon/files/12421308/mountaincliffnifs.zip)

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
In the future when creating issues, please don't forget to attach the nifs in question (easily done by putting them into a zip file and dragging and dropping them into the text box when going to edit the issue). I happen to have Skyrim SE, but not everyone who works on the plugin does.

**Comment by LarryBoi** [comment]
> In the future when creating issues, please don't forget to attach the nifs in question (easily done by putting them into a zip file and dragging and dropping them into the text box when going to edit the issue). I happen to have Skyrim SE, but not everyone who works on the addon does.

Apologies, I've attached the nifs in the issue and will remember to include in the future!
