### ISSUE TITLE
There is a problem with the install function

### ISSUE THREAD

**Issue by mirkiss** [niftools/blender_niftools_addon#600]
After running makezip.bat, an error is reported in the Windows system

```Destination : C:\BLENDE~1\install\blender_niftools_addon-v0.1.1-2023/08/25-.zip
使用“5”个参数调用“CreateFromDirectory”时发生异常:“未能找到路径“C:\blender_nif_plugin-develop\install\blender_nift
ools_addon-v0.1.1-2023\08\25-.zip”的一部分。”
所在位置 C:\blender_nif_plugin-develop\install\zip.ps1:29 字符: 1
+ [io.compression.zipfile]::CreateFromDirectory($source, $destination,  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DirectoryNotFoundException```

**Comment by mirkiss** [comment]
param (
    [string]$source,
    [string]$destination
)

# Correct path separator
$source = $source.Replace("/", "\")
$destination = $destination.Replace("/", "\")

write ("Source : {0}" -f $source)
write ("Destination : {0}" -f $destination)

If (Test-Path $destination) {
    write ("Ensuring existing archive is removed : {0}" -f $destination)
    Remove-Item $destination
    write ("Existing archive removed successfully")
}

Add-Type -assembly "system.io.compression.filesystem"

$EncoderClass=@"
  public class FixedEncoder : System.Text.UTF8Encoding {
    public FixedEncoder() : base(true) { }
    public override byte[] GetBytes(string s) {
      s = s.Replace("\\", "/");
      return base.GetBytes(s);
    }
  }
"@
Add-Type -TypeDefinition $EncoderClass

$Encoder = New-Object FixedEncoder

# Ensure that the directory structure exists
$directoryPath = Split-Path $destination -Parent
if (-not (Test-Path $directoryPath)) {
    New-Item -Path $directoryPath -ItemType Directory
}

[io.compression.zipfile]::CreateFromDirectory($source, $destination, [System.IO.Compression.CompressionLevel]::Optimal, $true, $Encoder)

If (Test-Path $destination) {
    write("File successfully written")
}
------------------------------------------------------------------------------------------------------------
Temporarily resolved the issue after modifying the code，
Modified the 'zip. ps1' file.

**Comment by Candoran2** [comment]
I've changed your comments to make the code more legible.

I think the problem here is that your date format appears to be YYYY\MM\DD (or YYYY/MM/DD), and those slashes are being interpreted as directory separators. The real solution would be to use something other than `echo %date%` in order to get the date, that is not dependent on local settings.

**Comment by mirkiss** [comment]
> I've changed your comments to make the code more legible.
> 
> I think the problem here is that your date format appears to be YYYY\MM\DD (or YYYY/MM/DD), and those slashes are being interpreted as directory separators. The real solution would be to use something other than `echo %date%` in order to get the date, that is not dependent on local settings.



You are a good person. Thank you for your enthusiastic support of this plugin.
