### ISSUE TITLE
AssertionError: shape (0,) doesn't match (xxxx,) on <class 'generated.array.Array'> when export nif

### ISSUE THREAD

**Issue by WenrenHe** [niftools/blender_niftools_addon#609]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
I have editted an nif mesh, change it's pose, append modifier, edit some vertexes, then export. Then an error occured.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
0.1.0
### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
Blender 3.6.3

### Platform information
**[Provide a brief overview of what OS your running on]**
windows 11 22621.2283

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 
1. import nif from a mod
2. poses, mesh edit
3. export

## Expected Result
**[Describe what you expected to have resulted from this process]**

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
AssertionError: shape (0,) doesn't match (5106,) on <class 'generated.array.Array'>
## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**
<img width="1280" alt="image" src="https://github.com/niftools/blender_niftools_addon/assets/109809690/c66d5253-820a-4c4d-9ba9-f96aa4774c99">

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**
`niftools:INFO:Dev: Sys variable not set
INFO:niftools:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.1.0(running on Blender 3.6.3, Nif xml version 0.9.3.0)
INFO:niftools:Executing - Niftools : Blender Niftools Addon v0.1.0(running on Blender 3.6.3, Nif xml version 0.9.3.0)
niftools:INFO:Exporting C:\Modding\MO2\mods\1three-eyed swallowSE\meshes\1Swallow\SwallowBootsF_1.nif
INFO:niftools:Exporting C:\Modding\MO2\mods\1three-eyed swallowSE\meshes\1Swallow\SwallowBootsF_1.nif
niftools:INFO:Exporting
INFO:niftools:Exporting
niftools:INFO:Exporting geometry and animation
INFO:niftools:Exporting geometry and animation
niftools:INFO:Writing NIF version 0x14020007
INFO:niftools:Writing NIF version 0x14020007
niftools:INFO:Exporting <bpy_struct, Object("awdawadwadwad") at 0x000001DDAF104808> as NiNode block
INFO:niftools:Exporting <bpy_struct, Object("awdawadwadwad") at 0x000001DDAF104808> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Calf [Clf].R") at 0x000001DDAEE2A948> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Calf [Clf].R") at 0x000001DDAEE2A948> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Foot [ft ].L") at 0x000001DDAEE2A788> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Foot [ft ].L") at 0x000001DDAEE2A788> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Thigh [Thg].R") at 0x000001DDAEE2A5C8> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Thigh [Thg].R") at 0x000001DDAEE2A5C8> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Thigh [Thg].L") at 0x000001DDAEE2A408> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Thigh [Thg].L") at 0x000001DDAEE2A408> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Foot [ft ].R") at 0x000001DDAEE2A248> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Foot [ft ].R") at 0x000001DDAEE2A248> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Toe0 [Toe].R") at 0x000001DDAEE2A088> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Toe0 [Toe].R") at 0x000001DDAEE2A088> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Calf [Clf].L") at 0x000001DDAEE29EC8> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Calf [Clf].L") at 0x000001DDAEE29EC8> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("NPC Toe0 [Toe].L") at 0x000001DDAEE29D08> as NiNode block
INFO:niftools:Exporting <bpy_struct, Bone("NPC Toe0 [Toe].L") at 0x000001DDAEE29D08> as NiNode block
niftools:INFO:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108>
INFO:niftools:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108>
niftools:INFO:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiTriShape block
INFO:niftools:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiTriShape block
niftools:INFO:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiTriShapeData block
INFO:niftools:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiTriShapeData block
niftools:INFO:Exporting NiSpecularProperty block
INFO:niftools:Exporting NiSpecularProperty block
niftools:INFO:Exporting NiMaterialProperty block
INFO:niftools:Exporting NiMaterialProperty block
niftools:INFO:Exporting <bpy_struct, ShaderNodeTexImage("Image Texture") at 0x000001DDAEA3B108, evaluated> as NiSourceTexture block
INFO:niftools:Exporting <bpy_struct, ShaderNodeTexImage("Image Texture") at 0x000001DDAEA3B108, evaluated> as NiSourceTexture block
niftools:INFO:Exporting <bpy_struct, ShaderNodeTexImage("Image Texture.001") at 0x000001DDAEA3A388, evaluated> as NiSourceTexture block
INFO:niftools:Exporting <bpy_struct, ShaderNodeTexImage("Image Texture.001") at 0x000001DDAEA3A388, evaluated> as NiSourceTexture block
niftools:INFO:Exporting NiTexturingProperty block
INFO:niftools:Exporting NiTexturingProperty block
WARNING:root:Field vertex_colors was not evaluated to be on type NiTriShapeData
niftools:INFO:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiSkinInstance block
INFO:niftools:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiSkinInstance block
niftools:INFO:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiSkinData block
INFO:niftools:Exporting <bpy_struct, Object("2.002") at 0x000001DDAF104108> as NiSkinData block
niftools:INFO:Creating skin partition
INFO:niftools:Creating skin partition
WARNING:root:Field strips was not evaluated to be on type SkinPartition
niftools:INFO:Checking collision
INFO:niftools:Checking collision
niftools:INFO:Checking controllers
INFO:niftools:Checking controllers
niftools:INFO:Scale Correction set to 10
INFO:niftools:Scale Correction set to 10
pyffi.toaster:INFO:--- fix_scale ---
INFO:pyffi.toaster:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 10.000000
INFO:pyffi.toaster:  scaling by factor 10.000000
pyffi.toaster:INFO:  ~~~ NiNode [awdawadwadwad] ~~~
INFO:pyffi.toaster:  ~~~ NiNode [awdawadwadwad] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC R Calf [RClf]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC R Calf [RClf]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC L Foot [Lft ]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC L Foot [Lft ]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC R Thigh [RThg]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC R Thigh [RThg]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC L Thigh [LThg]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC L Thigh [LThg]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC R Foot [Rft ]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC R Foot [Rft ]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC R Toe0 [RToe]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC R Toe0 [RToe]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC L Calf [LClf]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC L Calf [LClf]] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [NPC L Toe0 [LToe]] ~~~
INFO:pyffi.toaster:    ~~~ NiNode [NPC L Toe0 [LToe]] ~~~
pyffi.toaster:INFO:    ~~~ NiTriShape [2.002] ~~~
INFO:pyffi.toaster:    ~~~ NiTriShape [2.002] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShapeData [] ~~~
INFO:pyffi.toaster:      ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:      ~~~ NiSkinInstance [] ~~~
INFO:pyffi.toaster:      ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinData [] ~~~
INFO:pyffi.toaster:        ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinPartition [] ~~~
INFO:pyffi.toaster:        ~~~ NiSkinPartition [] ~~~
niftools:INFO:Writing .nif file
INFO:niftools:Writing .nif file
ERROR:root:validation failed on <class 'generated.array.Array'>[<class 'generated.formats.nif.nimain.structs.Triangle.Triangle'>]
ERROR:root:validation failed on field triangles_copy on type <class 'generated.formats.nif.nimain.structs.SkinPartition.SkinPartition'>
ERROR:root:validation failed on field 0 on type <class 'generated.array.Array'>[<class 'generated.formats.nif.nimain.structs.SkinPartition.SkinPartition'>]
ERROR:root:validation failed on field partitions on type <class 'generated.formats.nif.nimain.niobjects.NiSkinPartition.NiSkinPartition'>
Traceback (most recent call last):
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_export.py", line 271, in execute
    data.validate()
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 619, in validate
    type(block).validate_instance(block, self, arg=0, template=None)
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 247, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 226, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 247, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\win11\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 219, in validate_instance
    assert instance.shape == shape, f"shape {instance.shape} doesn't match {shape} on {cls}"
AssertionError: shape (0,) doesn't match (5106,) on <class 'generated.array.Array'>`
### Blend File
**[Attach the blend file if the issue is reproducible]**
file needed to export as nif: [https://drive.google.com/file/d/1p2tayKwc0vABd_7vMD7Hp8zNX7t_2QIj/view?usp=sharing](url)

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
import file: [https://drive.google.com/file/d/1ebPs-KVcIqUAJcPYoOlbn7OdnWWzXo8V/view?usp=sharing](url)

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
For which game are you trying to export?

**Comment by ArtezzaMagnet** [comment]
Not the one who opened this ticket, but just some additional information I can provide since I'm also running into this problem:

Versions tried:
3.5.1
3.6.0
3.6.4

Options tested with on and off:
- Issue still persists if "stitch strips", "force dds" and "optimise materials" are disabled.
- Issue **stops** happening if skin partition is disabled. Max partition bones set to 18, max vertex bones set to 4.

**Comment by Candoran2** [comment]
> In response to the above question: in my case, the initial imported nif was intended for Skyrim, but I haven't noticed any game specific options for exporting.

I asked because that error usually happens when trying to export for Skyrim SE (in the scene tab you can set the game). Since the addon doesn't support Skyrim SE export yet, you'll get that error. The current workaround is to set the game to just Skyrim before exporting. Skyrim SE usually is able to use those LE nifs just fine, but if you must have them in SE format you can also convert them from LE format to SE format afterwards.

**Comment by WenrenHe** [comment]
> For which game are you trying to export?

Skyrim AE 16640

**Comment by WenrenHe** [comment]
> > In response to the above question: in my case, the initial imported nif was intended for Skyrim, but I haven't noticed any game specific options for exporting.
> 
> I asked because that error usually happens when trying to export for Skyrim SE (in the scene tab you can set the game). Since the addon doesn't support Skyrim SE export yet, you'll get that error. The current workaround is to set the game to just Skyrim before exporting. Skyrim SE usually is able to use those LE nifs just fine, but if you must have them in SE format you can also convert them from LE format to SE format afterwards.

Tysm. I'll give it shot later.

**Comment by WenrenHe** [comment]
> > > In response to the above question: in my case, the initial imported nif was intended for Skyrim, but I haven't noticed any game specific options for exporting.
> > 
> > 
> > I asked because that error usually happens when trying to export for Skyrim SE (in the scene tab you can set the game). Since the addon doesn't support Skyrim SE export yet, you'll get that error. The current workaround is to set the game to just Skyrim before exporting. Skyrim SE usually is able to use those LE nifs just fine, but if you must have them in SE format you can also convert them from LE format to SE format afterwards.
> 
> Tysm. I'll give it shot later.

Well i tried to switch to "Skyrim" other than "Skyrim SE" in secne tab, then export. A new error occurs: 
<img width="630" alt="image" src="https://github.com/niftools/blender_niftools_addon/assets/109809690/b9a53645-b035-44c9-9c2e-4b6956c5ee0a">

Looks like the question is organizing meshes, too late now. Im fresh blood of meshing, will try it later. thx agin ;>

**Comment by WenrenHe** [comment]
> Not the one who opened this ticket, but just some additional information I can provide since I'm also running into this problem:
> 
> Versions tried: 3.5.1 3.6.0 3.6.4
> 
> Options tested with on and off:
> 
> * Issue still persists if "stitch strips", "force dds" and "optimise materials" are disabled.
> * Issue **stops** happening if skin partition is disabled.
> 
> Edit: In response to the above question: in my case, the initial imported nif was intended for Skyrim, but I haven't noticed any game specific options for exporting.

Still confused, where is skin partition option?

**Comment by Candoran2** [comment]
> Still confused, where is skin partition option?

The partitions can be assigned by giving the mesh face maps of the appropriate names and assigning the faces to them.

**Comment by WenrenHe** [comment]
> Try to download ''SSE NIF Optimizer'' Optimise your mesh for LE then try to import and export the mesh with blender, you may have to optimise back to SSE after export but i'm not sure

It works! Tysm!

**Comment by WenrenHe** [comment]
In my case, it doesn't matter whether importin mesh in SE or LE format.
What's makes sense is, export in SE, cause I want the skin parcition option.
I can transfer the mesh to SE with SSE NIF Optimizer. Then everything done.
