### ISSUE TITLE
Export NIF Not Working

### ISSUE THREAD

**Issue by ToolsnSwords** [niftools/blender_niftools_addon#620]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [x] Read the user documentation.
 - [x] Check that the issue hasn't already been reported.
 - [x] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

To Whom This Concerns,

I'm fairly new to blender and have run into this problem straight away, I have imported the NIF perfectly fine from Oblivion and have worked on it how I needed too and run into a python error every time I try export it is this an issue with what release im using or is it something else.

My Thanks 

E

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**

Blender Niftools Addon - v0.1.1

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**

 Blender 4.0

### Platform information
**[Provide a brief overview of what OS your running on]**

Windows 11

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

Export

## Expected Result
**[Describe what you expected to have resulted from this process]**

My Blender file to export to a NIF.

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**

See screenshot section.

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

![Screenshot 2023-11-21 201231](https://github.com/niftools/blender_niftools_addon/assets/151679446/55afeebc-106f-4b5e-bfd2-bd70a7e14398)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
N/A

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Candoran2** [comment]
This seems to be a consequence of updates to the Python API that were done in Blender 4.0. You could try Blender 3.6 in the meantime.

**Comment by ToolsnSwords** [comment]
Thank you for the prompt reply! I will try that now and will update you if it works :)

**Comment by ToolsnSwords** [comment]
That worked a charm! thanks for the help and hope you have a great day!
