### ISSUE TITLE
Sub Issue : #26 : Separate Normal data from Material code

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_niftools_addon#75]
Code requires a material to execute geometry code related to normal data generation; normal, tangent, bi-tangent. 
This results in no normal data being generated

Ref Summary #26 

Causes Geometry based tests fail due to requirement that material be added to the geometry. 
See issue #22  for summary

**Comment by HENDRIX-ZT2** [comment]
Pretty sure it's done, too?

**Comment by neomonkeus** [comment]
Will include in release summary.
