### ISSUE TITLE
Sub Issue : #26 : Separate UV import/export from Material code

### ISSUE THREAD

**Issue by neomonkeus** [niftools/blender_niftools_addon#76]
Geometry based tests fail due to requirement that a material must exist for the data be added to the geometry.
See issue #22 for summary

Code requires a material to execute geometry code related to uv data generation; uv_sets, 

Results in no uv data being generated without material present.

Ref Summary #26

**Comment by HENDRIX-ZT2** [comment]
Pretty sure this is done?

**Comment by neomonkeus** [comment]
Will include in changelog for v0.0.13
